### ISSUE TITLE
Field Display shows blank screens when user on Match Control screen clicks either "Show Preview" or "Video Switch->Show Sponsors"

### ISSUE THREAD

**Issue by Tomrish** [FIRST-Tech-Challenge/scorekeeper#102]
As you've probably figured out from the title, the Field Display shows blank screens when user on Match Control screen clicks either "Show Preview" or "Video Switch->Show Sponsors". This directly affects the setup we have for a scrimmage that we are running in December, and I have been thinking that **_maybe_** it **_possibly_** could be meant to be a blank screen, but the way that the blank screen was laid out looked unfinished, so it would have to be fixed either way. Attached is a video recording of the exact issue that I'm seeing as well as the db folder of the match control computer.
[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2499971/db.zip)
[Video.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2499973/Video.zip)

**Comment by adwiii** [comment]
Major props for the video - that is amazingly helpful for debugging things like this to make sure we are on the same page discussing all of the different screens.

The Field Display was not intended to show the Match Preview. It is a bug that it shows the blank screen - it should have ignored the command to show the Match Preview. If you want the Field Display to show the Match Preview, this requires advanced settings (documentation coming soon). To achieve this behavior, select the "Enable Advanced Settings" checkbox and then select the appearance as "Field Display" and the Behavior as "Audience Display". This will cause the Field Display to show the same things that the AD would show such as Match preview and Match results, but still retain the large clock display element of a Field Display.
![image](https://user-images.githubusercontent.com/9453262/47298670-61837680-d5e6-11e8-9137-992ebd3dd0fe.png)


The Field Display (when not using advanced settings) does ignore the command for sponsors. The reason it showed the blank screen for you is that the blank screen was the last thing to be shown, so it simply ignored the sponsors command and continued showing the blank screen.

From this I believe there are two action items:
1. Update the documentation to clarify the intent of Field Display and Audience Display behavior and how to use the advanced settings.
2. Fix the Field Display to not show the blank screen on preview, instead it will ignore the command and continue displaying what it displayed last.

**Would those two things solve your issue?**

If you want more explanation as to why the default behavior is the way it is, read on.

Alternatively, we could make it so that the Field Display always shows Match Preview and Match Results. However, the reason this is not the default behavior is because the Field Display shows the randomization as soon as it is known. At a one field event this is not an issue - the Scorekeeper would hit "Show Preview" to update the Audience Display, then shortly thereafter press "Randomize Field" which would cause the Field Display to immediately show the randomization while the Audience Display continued to show the preview. Then, if the Scorekeeper wanted to show the randomization to the audience, they could hit the "Show Random" button to show it on the Audience Display. In this scenario there would be no difficulty in showing the Match Preview on the Field Display. The complication comes when using two fields at an event. The system will let you load the match on Field 2 for play and randomize the field before the match on Field 1 has finished, which causes the Field Display for Field 2 to show the randomization while the other match is running. However, it will not let you show the preview since there is a match running and we do not want the Audience Display to stop showing the active match. This means that before the Match Preview has been shown, the randomization is already being displayed on the Field Display for Field 2. Then, sending the command to show the Match Preview would cause the randomization to stop being displayed, which could interrupt the referees setting up that field. I understand this is more of an advanced set up, but the idea behind the behavior of Field Display and Audience Display was "Field Display only shows the timer and randomization since those are all that is necessary to run the field" and "Audience Display shows everything that can be displayed."

**Comment by Tomrish** [comment]
Thanks for the help! I'll be reading this in more detail as soon as I get some spare time, but I'll be sure to let you know if there's anything else to add.

**Comment by adwiii** [comment]
The blank screen issue has been fixed
