### ISSUE TITLE
API Suggestion: Return All matches in the match list

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#113]
At TOA, when the user requests the match list, the API returns all of the matches (elims included) with match level identifier, such as 
1 = qual
2 = semis
3 = finals
and then the match number was 
Semis 1-1 = 11
Semis 1-2 = 12

**Comment by cmacfarl** [comment]
Elimination matches don't exist until alliance selection is done.  Hence there's nothing to return.  The server could create an empty bracket, but that is kind of a waste of bytes on the wire.  If a client wants an empty bracket it can generate one itself.

Additionally, it's impossible to know exactly how many elimination matches are going to be played in any given series as the third match is dependent upon the outcome of the second match.   And, the match list given to teams, always, and only, contains qualification matches.

If you think this is something that deserves more discussion, please feel free to elaborate, otherwise please consider closing this issue.

**Comment by Techno11** [comment]
At TOA we don't return any elim data until it is available, you could do the same. Saves on the user having to do /event/<eventid>/matches, find all matches have been played, then go to the other endpoint.  Easier to just not return elim data until it is available.

**Comment by afera15** [comment]
First can we merge this with Issue #115 
I agree with @Techno11 , FRC Handles Matches the same way we do (Except we combine the Schedule and Results):

> The match results API returns the match results for all matches of a particular event in a particular season. Match results are only available once a match has been played, retrieving info about future matches requires the event schedule API. You cannot receive data about a match that is in progress. You can, however, request the Hybrid Schedule if you would like data about upcoming and played matches at the same time.

Having it in the same return is easier so we don't need to do the same request 3 times and do another request and figure out who is vs who, FRC will put the Quarter Schedule out after Alliance selection and then each other level after the previous one was completed.  

Lastly if FIRST opinion isn't for us to assume anything would you want us to us your calculation of who is playing who instead of leaving it up to us as third party to calculate this ourselves per your wording on ranking: 

> Applications must not generate their own rankings from match data.without explicitly labelling them as not event official.

**Comment by afera15** [comment]
@adwiii Just an FYI in your `apiv1/events/<event_code>/matches/<number>/` route you do actually can get enough information for generating the rankings unless I missed something in the rules

> At the conclusion of each match, Ranking Points and TieBreaker Points are awarded:
> • Teams receive Ranking Points based on the following:
> o Winning Teams of a Qualification Match each receive two (2) Ranking Points.
> o Losing Teams of a Qualification Match receive zero (0) Ranking Points.
> o If a Qualification Match ends in a tie, all four Teams receive one (1) Ranking Point.
> o If a Team is disqualified or does not show up for a match, they receive zero (0) Ranking Points.
> • TieBreaker Points are awarded based on the following:
> FIRST® Tech Challenge Game Manual Part 1 | 17
> Gracious Professionalism®
> - “Doing your best work while treating others with respect and kindness - It’s what makes FIRST, first.”
> o The number of TieBreaker Points assigned for each match is that of the losing Alliance’s score.
> Both Alliances receive the pre-penalized score of the losing Alliance as their TieBreaker Points.
> o If a match ends in a tie, both Alliances receive the same number of TieBreaker Points, equal to
> the lowest pre-penalized score. If a Team is disqualified, they receive zero (0) TieBreaker
> Points.
> o If both Teams on an Alliance are disqualified, the Teams on the winning Alliance are awarded
> their own score as their TieBreaker Points for that match.

It's just better and less chances of a mistake if you do it through the official application like should be done for the schedule of the elim matches

**Comment by Techno11** [comment]
Please open another issue for your ranking discussion.  This issue is for something else. Thanks @afera.

**Comment by adwiii** [comment]
@afera15 
>  After all *Qualification Matches*, the *Teams* are ranked from first through last based on their total *Ranking Points*. If multiple *Teams* have the same *Ranking Points* total, these *Teams* are ranked based on their total *TieBreaker Points*. If multiple *Teams* have the same *TieBreaker Points* total as well, then these *Teams* are ranked based on their highest match score. If still tied, the next highest match score is used until the tie is broken. **In the unlikely event there is still a tie based on identical match scores, then the *Teams* are ranked by a random electronic draw. These rankings are done automatically through the scoring system software.**


If there is a tie, then the scoring system is the only official system that can randomly break the tie. If a third party application attempts to break the tie through a random electronic draw, and chooses differently than the official scoring software, then different, incorrect, rankings will be created. Thus, the scoring system is the only way for official rankings to be produced, because it is possible that the steps you outlined above are insufficient to provide a strict order on the teams.

Sorry @Techno11, but I hope is sufficient on the rankings end of things.

**Comment by afera15** [comment]
@adwiii @Techno11 I am not trying to say that a third party app should I am trying to show an example of why generating it yourself and not pulling from the scoring system is a bad idea which is why Elims schedule should be in the `apiv1/events/<event_code>/matches/`

**Comment by ofekashery** [comment]
Any update?

**Comment by Techno11** [comment]
Ignoring what Alex said that was very off-topic, this could still be very useful.  Is it possible to add a route to return all? such as `/matches/all`?  Thanks!

**Comment by adwiii** [comment]
A single route that returns all matches is not very efficient as the eliminations list and qualifications list cannot both be dynamic at the same time. Alliance selection is the critical switching point - before then there cannot be any eliminations matches and after then there cannot be any qualification matches. 

For events doing live uploading, we would like to keep the footprint of the API as light as possible and as such would like to encourage usage of endpoints that result in small amounts of data. To this end, during eliminations we do not want third parties pulling the entire qualification schedule if it is not needed and stick with the current implementations.

For third party applications that are polling the system after the fact to gather information on the state of the event, the new API routes `/api/v2/events/{code}/full` and `/api/2020/v1/events/{code}/full/` can be used to quickly find all of the information about the event, including both the qualification matches and eliminations matches. However, this cannot and should not be used while the system is running the event and there is a very strict rate limit in place (currently combined 4 requests per 30 minutes).
