### ISSUE TITLE
Report Scorekeeper Version in API endpoint

### ISSUE THREAD

**Issue by smo-key** [FIRST-Tech-Challenge/scorekeeper#128]
Things are changing fairly quickly in this project and, unfortunately, not all events will stay up-to-date with the latest release. There needs to be a way to know what capabilities the scorekeeper software has to allow 3rd-party solutions to maintain backward-compatibility with the scorekeeper software.

I propose adding a `GET /apiv1/version` endpoint that identifies the API. Response should be JSON as in the minimal example below.

```
{ version: "0.4.3" }
```

`Content-Type` header is expected to have value of `application/json`.

**Comment by adwiii** [comment]
We will add something to this effect. Long term we hope that the API can be stable enough that using `apiv1` etc. is sufficient versioning, but I recognize that this is not feasible in the new term.

**Comment by cmacfarl** [comment]
Seems reasonable.  The way it's designed, if the response changes for any shipped endpoint, then that endpoint needs to live off of a new apiv<X> root so that you don't break existing clients.   Entirely new endpoints may live off the existing, most recent apiv<X> root. 

Clients can query for the version to determine which endpoints are supported.    Version always returns the version of the scorekeeping software, not the version of the api.   Clients would have to keep track of what was introduced in each release.  

Comments?  Concerns with this approach?

**Comment by adwiii** [comment]
This has been added in 0.5.2
