### ISSUE TITLE
Score Tracker - Autonomous Screen allows values higher than game max value.

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#13]
Score Tracker – Autonomous Screen: Left Cargo Hold, Right Cargo Hold, and Minerals in Depot allows values higher than game maximum value.

**Comment by cmacfarl** [comment]
This issue speaks to accuracy of scoretrackers, not necessarily correctness of software.   If we have a scoretracker that is inaccurate, then software can't ensure accuracy by capping mineral counts.  In fact, I'd argue that a cap on mineral counts will not result in any fewer inaccurate match scores over the course of a season/event than would happen without a cap.

**Comment by slacter** [comment]
It would be appropriate to cap the values to aid the score tracker in their understanding of the limits of the game, especially those who are new, and to prevent some of the errors.  An important rule of user interfaces and the human element: if it can be abused, it will be abused, even with good intentions and review, but mostly with malice.  If software can prevent an issue with reasonable effort, it would be best to implement that prevention measure.

**Comment by adwiii** [comment]
The simplest answer is that I don't know that the limits are as hard and fast as we would like. A few considerations:
1. If there are more than the Game Manual specified number of pieces on the field, does that mean that some of the pieces are not allowed to be scored? The Game Manual does not say, so I do not believe it is the place of the scoring software to enforce a hard cap.
2. The limits are for the entire *field* - this would mean that to enforce limits then the different score tracker pages would need to talk to each other, which is an extra layer of complication for little gain in my opinion.
3. We don't know the exact state of the field. The Gold and Silver are counted separately when scored in the Lander, but when they are in the Depot then we don't know which one is which. As such, it would be very difficult for us to make any limits other than aggregating everything together and saying "this is not valid, but I can't tell you where the error is".
4. Related to number 3 - where is the error enforced? Do I limit you so that if you have scored all of the Gold on the field into your lander then you can only score the limit of the number of Silver on the field into the Depot?

If we have malice on the part of scoretrackers then I would argue the game is lost - they could always start assigning penalties until whoever they want to has won.

We can add limits such that each individual location only allows the maximum that could possibly be in that location, but that still allows for "invalid" field states overall, so I don't know that you really gain anything by enforcing it on a per field basis.

**Comment by slacter** [comment]
_I would argue only for the maximum for a particular scoring location, prioritizing this limitation to those fields where the max count would be less than 10._  There would be no need to go into further programming complication, and I believe it properly addresses the OP's original concern.

I've programmed a method of cross-communication between fields for total count possible in other games, but it tends to cause unwarranted complication for the score tracker, particularly when they can't understand why they can't add one element in one field when the total maximum is hit across all fields.  So I would argue against doing any complicated evaluations stated in #2-4.

As for malice, it would be more inconspicuous for a biased score tracker to add or remove just one more element on a close game to help their favored side win, but I agree this would be very difficult to enforce in software.

**Comment by adwiii** [comment]
For SKYSTONE we have chosen to add several safeguards for impossible scoring states, but do not track the total number of Stones in play. See #200
