### ISSUE TITLE
transfer sponsors from older version to newer version of software

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#136]
How do you transfer sponsor info that was input to an older version of the software to a new version of the software.  I tried moving the global.db and server.db files from the older system to the newer one but the sponsor info didn't copy over.

**Comment by adwiii** [comment]
There is currently no way to import sponsors, though I know the import sponsor button is on the sponsor page - it just does not do anything. This is a work in progress, my apologies for the confusion and inconvenience.

Sponsors are stored on the event level for that event only, which is why copying global and server did not copy over the sponsors.

**Comment by adwiii** [comment]
The sponsor system has been changed this year to only include a list of the names of the sponsors for "Regional" and "Event" level. To import to a different event, you can import the event database of the previous event on the sponsor page:
![image](https://user-images.githubusercontent.com/9453262/64706947-4a5caa00-d480-11e9-91b4-3be91e7108a5.png)

Note: this only works with databases from v1.0.0 on.
