### ISSUE TITLE
Add start match time to API match detail route

### ISSUE THREAD

**Issue by afera15** [FIRST-Tech-Challenge/scorekeeper#141]
Can you add a time stamp to when the match was started to the API.

**Comment by afera15** [comment]
We want to know when the controller click the start match button.

Duplicate of #117, can be closed.

**Comment by adwiii** [comment]
#117 is not a duplicate - it asks for when the match was committed, which includes the latest edit time. If we want both features I would like two separate issues to track them because the system needs to handle them differently.

We can look into this, but I can't promise the start time of the match will be exposed any time soon. #117 is higher priority as it is guaranteed to be known and is useful in determining if data has changed. Knowing when the controller clicks start match is a luxury.

**Comment by adwiii** [comment]
This has been addressed in v1.0.0 (if I understand the issue correctly). See the updated [swagger documentation](https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation) for  more information.
