### ISSUE TITLE
Scoring/timing displays without login

### ISSUE THREAD

**Issue by rezafouladian** [FIRST-Tech-Challenge/scorekeeper#149]
One feature I would like to see is the ability to access the scoring/timing displays without having to login to an account. Our broadcast overlays and digital signage simply takes a URL and displays it, and ranges from difficult to impossible to interactively login.

**Comment by adwiii** [comment]
Will you be able to enter a URL easily enough if I give you a specific one? I'm trying to understand how limited access you have. We could do something like a special token in the URL that logs you in if that would work.

I don't want the pages to be entirely unprotected because the display pages put the highest load on the system of any page, and I want the user to at least have to acknowledge this by logging in. It's not a matter of data security so much as protecting the server from inadvertent extra load.

**Comment by rezafouladian** [comment]
Yes, the systems just take a URL and display it. Even if we could just put the username and password in the URL (like username:password or something) would be fine.

**Comment by adwiii** [comment]
Displays still require being logged in, but they can now be logged in using URL parameters. Append `?username=<username>&pw=<password>` to the display URL that has settings configured as you would like. This only works if the account that you are logging in as *only* has the Display permission. All of the auto-generated display accounts meet this criteria, but for example, the `local` user does not.
