### ISSUE TITLE
Unable to Upload previous Match Database

### ISSUE THREAD

**Issue by vedular** [FIRST-Tech-Challenge/scorekeeper#152]
We tried uploading our 4.0 DB database for our second scrimmage. We for the message Not Ok after providing the path of the file. We ran the tournament as a new using version 5.1. We need to somehow merge the first two database so that in third we need to start using the merge database and addon. Our Next tournament is on Nov 17. **T**his is a High priority Issue!!!****

**Comment by adwiii** [comment]
Can you please upload here the database you were trying to import (if you do not want to upload it here then you can email it directly, let me know). 

Also, what browser were you using for the upload?

**Comment by adwiii** [comment]
Also if you could upload the log file(s) here that would be helpful

**Comment by vedular** [comment]
Can you send me your email address I will send you the DB files? I am not sure what browser we use. I think it was IE. But I need to check again.

Thanks
Ram

**Comment by adwiii** [comment]
You can send the db and log files if you have them to ftcscorekeeper@gmail.com

**Comment by adwiii** [comment]
We looked into the db offline and found that Meet 1 had event type Scrimmage instead of event type League Meet. A Scrimmage archive file will not import into a league event.

For others that may have this issue: in version 0.5.1, you can now edit the event type. If you have created an event and marked it as a Scrimmage in error, then you can change it to a League Meet and re-download the archive file. Do note that the event type must be correct at the time of the download of the archive file.
