### ISSUE TITLE
Combined ranking details not always correct

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#168]
We have completed 3 meets. We have imported all of the match results and are ready for match 4.  Database files attached.

However, of our 16 teams, 3 show the wrong match count (they did not show for 3 matches in the first meet and only did one other meet) - they show 10 matches completed not 7. Teams names all start with RoboKnights (112, 15290, 15292).

In addition, we have 3 teams with incorrect RP counts. CircuitRunners Black (11347) should have 10 RP, not 12, TigerBytes (5991) should have 10 RP not 8, and RoboKnights 2 (15290) should have 6 RP not 8.

All team high scores align with the end of meet ranking reports from the 3 meets. We have not manually validated the TBP or manually verified the ranking data (RP, TBP, highest) within a given meet. But the teams usually scream at the scoring rapidly if we have an issue within the meet.

[roswellga-m1-3.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2549644/roswellga-m1-3.zip)

**Comment by adwiii** [comment]
Do you have the archive files that you imported into meet 4? Then, separately, can you load meet 2, export it again, and then send us that as well?

I agree that the meet 4 included in the zip has incorrect rankings. In fact, it appears that the match results used to calculate the rankings are incorrect in meet 4. However, when I export meets 1 through 3 and then import them into a new event, I have the rankings we expect to see, and I have verified that the match results are correct. It appears, as best I can tell, that the issue is that the imported data into meet for from meet 2 has incorrect results for matches 3 and 15. In these cases, it has the winners reversed for RP, no TBP was awarded for the match, and only the losing alliance got highest match score credit. Match 18 is also wrong, but only for the losing alliance.

If you want, I can post here a corrected meet 4. However, you already generated a schedule for meet 4 and it would take extra work to preserve that schedule. Let me know if you want us to post a corrected meet 4 and if you would like the schedule preserved.

**Comment by vwestin** [comment]
Here are the files I imported:

[Exports.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2550348/Exports.zip)

A fresh export of meet 2 is here:

[roswell_ga_m2-new.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2550349/roswell_ga_m2-new.zip)

I used a fresh export of meet 2 into a new event 4 and the data is all fine now. Having the team match history (as requested in #167 would help teams to watch for this sort of issue as we moved on to the next match. How else might we detect a corrupt export such as this?

**Comment by maths22** [comment]
League rankings have been reworking substantially since this season.
