### ISSUE TITLE
Option to see combined rankings is not available

### ISSUE THREAD

**Issue by khoyt5** [FIRST-Tech-Challenge/scorekeeper#177]
When I load the league meet, I am not given the Combined Ranking option. Is this due to files were generated from 0.4.1? Or is it some other reason? What needs to be done so that the Combined Ranking is available?

Attached are both league meet exports.
[nefl_meets.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2559720/nefl_meets.zip)

**Comment by adwiii** [comment]
If all you are worried about is importing into the next league, then everything is fine. the neflmeet2_final.db can be imported into any subsequent league event and will import correctly.

On the other hand, if you want to view the combined rankings as they stand after meet 2 without creating another event, then you need to import the neflmeet2_final into the server using the Manage Server option. See more detail below.

I am not entirely sure what this looks like on your end, but I can explain what it looks like to me and you can tell me if this matches up. 

If you renamed the file from #161 and then imported it into the new version of the server, then there were no combined rankings. The reason is that in older versions of the software (pre-0.4.0 I believe), the db file did not save with it what type of event it was and thus on import the server defaulted to the event being a scrimmage. I understand this is not what you would expect, and it this behavior has been corrected in later versions. 

Below is a long discussion about how to fix this yourself if you are interested. Otherwise I have fixed it and attached the correct db below. The attached db should work if imported into v0.5.1 (that is what I tested with).

To correct this locally you can import the db file, edit the event to have the League Meet type, and then pull the db out of the db folder. That is what I have done for the db below. Crucially, you *cannot* download the archive file, because that will cause duplicate league meet data - since the file was renamed neflmeet2_final from neflmeet2, on import the server treats them as different events and if you archive the data then it will create a new entry in the db for an event with code `neflmeet2_final` which has all of the same data as neflmeet2. A bit technical I know, but it stems from again this being from an older version of the system - all of the issues I have just described have been fixed in subsequent versions so that you do not have to go through these steps. 

[neflmeet2_final_with_combined.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2559750/neflmeet2_final_with_combined.zip)

**Comment by adwiii** [comment]
@khoyt5 please let me know if you have any other issues.
