### ISSUE TITLE
Not all the states of the Netherlands are in the scoring system

### ISSUE THREAD

**Issue by Rob4481** [FIRST-Tech-Challenge/scorekeeper#192]
When I create a league for in the Netherlands. I only have the option to choose a state out of 3 options.
I can choose FL, NB and ZH. But there are some league meets in other states.

Is it possible that all the states of the Netherlands can get added to the scoring system?

Here is the list of all the states:
Drenthe
Flevoland - FL
Friesland
Gelderland
Groningen
Limburg
Noord-Brabant - NB
Noord-Holland
Overijssel
Utrecht
Zeeland
Zuid-Holland - ZH

**Comment by adwiii** [comment]
I can tell you why this happens at least and we an look into working around this. The scoring system does not store a list of states for any country (nor does it store a list of countries for that matter). The system [has a list of all of the registered teams](https://www.firstinspires.org/team-event-search#type=teams&sort=name&programs=FTC&year=2018) that we update each release. From that list, it then makes a list of every country and state that has at least one team. Thus, it only presents to you states in the Netherlands which have at least one registered team. I assumed that there would never be a league that existed in a location that did not have a registered team, but that may not have been a good assumption. 

A few notes on leagues and the scoring system - a single event does not have a location associated with it. However, leagues do have an associated country, state, and city. This information is mainly for the benefit of those working with the league to keep track of it and fits with the notion that leagues are generally contained in a specific geographic area. All of the meets for that league do not need to take place in that geographic area, and the scoring system will not know the difference. 

Do you need to create a *league* that is based in a state that is not listed? Or do you have one league that is going to play some meets in a state that is not listed?

If you are interested, the scoring system determined that `FL, NB, ZH` were the available states in the Netherlands because it knows about the following teams from the Netherlands which have the corresponding states listed on their official registration:

| Team # | Team Name | State |
| -------- | ------------- | ----- |
| 12475 | Team Nova | NB |
| 12819 | The Outlanders | NB |
| 13953 | Stanislas Tech Team | ZH |
| 14381 | Dutch Warriors | NB |
| 14979 | HP S.A.S | FL |
| 15614 | Stanislas Tech Academy | ZH |

**Comment by Rob4481** [comment]
We have only 1 league meet that is in the state of Utrecht which is not listed. All the other league meets are in the states that are listed.

**Comment by adwiii** [comment]
Events, and thus meets, do not store where they take place. Can you elaborate as to why you need the other states in the system?

**Comment by adwiii** [comment]
I understand the desire to input a state, but I have a separate question. Are you creating a new league for every meet? If so, what is the league set up in the Neatherlands?

**Comment by Rob4481** [comment]
No, I created the leagues at the first event and after I upload the previous event results into a new event, those leagues get uploaded as well.

**Comment by adwiii** [comment]
I am confused how you have a league that is located in a place that has no teams. Can you explain the league set up in the Netherlands? Who is a part of each league? What events do these teams or leagues play in?

**Comment by Rob4481** [comment]
Previous years we held one big FTC regional where teams from all over the Netherlands could compete at. This year we have for the first time league meets. We have 4 league meets and 1 league tournament. the first league meet was at Stanislas College in Delft, Zuid-Holland (ZH). The second league meet was at Newman College in Breda, Noord-Brabant (NB). The third league meet is at Hogeschool Utrecht in Utrecht, in the state Utrecht (UT). League meet 4 is at Zwijsen College in Veghel, Noord-Brabant (NB) and the FTC Netherlands League Championship is at Maerlant-Lyceum in Den Haag, Zuid-Holland (ZH). The Netherlands isn't a big country so we have a lot of teams traveling to other states to compete in the league meets.
[https://ftcnetherlands.eu](url)

**Comment by adwiii** [comment]
League management is deprecated in FTCLive and all league data is handled through the [online scoring system](https://ftc-scoring.firstinspires.org) and automatically imported when the event is imported into FTCLive. When a league is created in the online scoring system, the location is entered in a text field, solving this issue. 

Events should be imported from the online scoring system. The online scoring system pulls its list of events from HQ, including the location information. Combined these should solve this issue.
