### ISSUE TITLE
Did not create a league during setup

### ISSUE THREAD

**Issue by rebeccawhitaker** [FIRST-Tech-Challenge/scorekeeper#207]
At one of the league meets, the scorekeeper did not "Create a League" and added teams individually. Can a league be created and these teams be added to it after the event so at future meet events it is easier to import data. The name of the League should be "Burnell"
[Burnell_2018-11-17_meet1.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2596035/Burnell_2018-11-17_meet1.zip)

**Comment by adwiii** [comment]
I have created a league in the event that you attached with the league code `burnell` and the league name `Burnell` and attached the resulting db below. I left the state, country, and city as the default (AE, USA, blank city), so you might want to change those, but you do not have to change them. If you do not make any changes, then the db that I have attached will be fine for import at your next event.

[burnell_meet1_18.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2596093/burnell_meet1_18.zip)

If you want to change anything about it, import the event ("Event Admin" (in header)->"Manage Server"->"Choose File" (under "Data Import")) and then go to the Event Dashboard and the "Manage Leagues" page, then select "Edit" next to the league. From there you can change the event name, city, state, and team list. I assumed that the only teams in the league were the ones at the event. If there were more teams in the league that were not at the event, you can add them by going to the "Add/Remove Teams" page from the edit page for the league. If you change the team list, reboot the server before proceeding. After you have made whatever changes you want, you can download the archive for the `burnell_meet1_18` and it will be suitable for import into your next event.

**Comment by slacter** [comment]
Ditto!  Can you help with this one?  What method are you using to "fix" the file?  League name "Camilla"
[CamillaLeague_Meet2_20181103.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2601539/CamillaLeague_Meet2_20181103.zip)

**Comment by adwiii** [comment]
You can add a league at any point in the event, including after the event has happened. Once you have imported the event, go to the event dashboard and create the league as you would as if it was during the event setup. In the case of adding the league after matches have been played, you need to reboot the server for the changes to be visible - the rankings will display incorrectly without a reboot, but the data is stored correctly. We will be fixing it in a future release so that you don't have to reboot the server after, but for now you do.

@slacter The name of your event implies that there was an Meet 1 that should be imported into this event in order to see the complete rankings across both events. Doing this import would also import any League that was contained in Meet 1. It is okay for you to not import Meet 1 into Meet 2 just so long as at the League Tournament all of the data gets imported, but it may be easier to manage the League data if you utilize the import feature. Since this would remove the need to create an League at subsequent Meets.

One note: the league does not need to exist in the event for the data to be properly transferred to the next event. The league is only needed for the purposes of viewing League Rankings using the data from the current event.

Let me know if you have any other questions.

**Comment by slacter** [comment]
I created the league and restarted the server.  The rankings appeared as you have stated.  (As for Meet 1, it has not occurred, yet.  They rescheduled it to a later date.)  Thank you for the feedback!

**Comment by tcflanag** [comment]
I had two different leagues in my region make the same mistake.  Should there be a check in place to prevent this?

**Comment by jvens** [comment]
One option would be during event creation if the user selects event type of `League Meet` or `League Tournament` it would take the user to the `Manage League` page instead of the `Event Dashboard`.

Also, I am not positive, but it seems to me that there should never be a use case where a league event would have a reason to add a team that is not in one of the leagues associated with the event.  Therefore, you could simply disable that feature and only allow the `Add/Edit Teams` page of the dashboard to `Find by League` and disable the other tabs.

**Comment by tcflanag** [comment]
Is there any reason to let the user skip the league creation step for League type event?  Shouldn't all following steps be disabled until that is done?

**Comment by adwiii** [comment]
Closing as league management is deprecated in FTCLive. All league data is handled through the [online scoring system](https://ftc-scoring.firstinspires.org) and automatically imported when the event is imported into FTCLive.
