### ISSUE TITLE
Suggestion: Add scoring details to sides of the Field Display

### ISSUE THREAD

**Issue by cheer4ftc** [FIRST-Tech-Challenge/scorekeeper#213]
Right now, there is a lot of blank space on the sides of the Field Display next to the Timer. 

The Audience Display shows lots of great info regarding how the match has been scored.

It would be great if this audience display info could also be shown on the sides of the field display. This would allow the teams to quickly double-check the scoring at the end of the match, and to quickly raise any errors they may see with the scoring ref before the score is committed (e.g., "we didn't get our Latching End Game points").

**Comment by adwiii** [comment]
We are working on adding scoring info to the Field Display and Video Overlay. However, the plan is to put the scoring info in the bottom bar next to where team numbers are shown for both of them. On the Video Overlay we have to put them there because the top portion is reserved for the video itself. On the Field Display we want them at the bottom because the purpose of the Field Display is to be a large timer that the teams can focus on. 

If event managers/teams at events agree that they would rather have full scoring information instead of a large timer, then they could run the Audience Display beside the field.

**Comment by adwiii** [comment]
Accidentally hit the wrong button when commenting, sorry.

**Comment by cheer4ftc** [comment]
Thanks. Looking forward to seeing this info added on the Field Display at the bottom. One of our FTAs pointed out that using the Audience Display instead beside the field may lead to problems (e.g., audience display is one display for all fields, so showing randomization for one field may confuse refs on another field that might think randomization has happened for their fields, timer would show for all fields and not just the specific field by the monitor, etc.)

**Comment by adwiii** [comment]
All displays can be bound to a specific field, including Audience Displays. If you want to run an Audience Display next to a field, then you should set the display to be bound to that field and then it will only display the match information for that field.

**Comment by cheer4ftc** [comment]
Cool. Will it also show randomization at the appropriate time, etc.?

**Comment by adwiii** [comment]
My bad, I pasted the wrong image above, this is what you want:
![image](https://user-images.githubusercontent.com/9453262/49232849-c048c680-f3c2-11e8-9118-dc28249a2347.png)

**Comment by djpirocchi** [comment]
I see my enhancement #171 was merged into this one.  I was looking for displaying that the Depot was completely claimed on the Field Display.  It currently, only shows on the Audience Display.   Are we saying the solution is to display the Audience Display at the fields and lock it to that field?  I am not sure how that will be received but will present it.

Or, are we waiting for a new version that includes more scoring elements in the bottom bar of the field display.  Preferred, IMO.

Thank you.

**Comment by adwiii** [comment]
For now if that is a requirement, then display the Audience Display bound to a field as described above. However, as I said above, I believe that teams should have input in this decision, because for teams having the large timer might take precedence over seeing each individual scoring element.

We will add the scoring elements to the bottom bar of the Field Display and Overlay, I just have not had time to do so yet.

**Comment by adwiii** [comment]
The scoring details have been added to the bottom of the Field Display and Overlay in 0.7.3. The icons are slightly different because of the reduced space. We are working on making a legend for the icons.
