### ISSUE TITLE
Randomization value stored as a '-1' in one match

### ISSUE THREAD

**Issue by slacter** [FIRST-Tech-Challenge/scorekeeper#217]
Discovered that one match stored the randomization value as negative one (-1).  Match was played on Nov. 3.

[acmeet3.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2633794/acmeet3.zip)

![neg_random](https://user-images.githubusercontent.com/25590943/49296078-4c232700-f485-11e8-82fb-cba3215d9f30.png)

**Comment by cmacfarl** [comment]
Randomization data is not exposed in the public API.  So there's no possibility of incorrect data on a third party site (Note that 3rd party sites are not supposed to be scraping the db directly).  The match was played.  This was a scorekeeper error.  Closing for this reason.  If you feel strongly that events which are not using live scoring and have enabled external randomization should enforce that this randomization is tracked properly, you may reopen this as an enhancement.

**Comment by slacter** [comment]
Makes sense.  Would it be prudent to not allow the start of a match without a ranomization value entered?

**Comment by adwiii** [comment]
If live scoring is disabled then the system does not need to know the randomization because it will never display the sampling field and thus we did not feel it necessary to make the user input the randomization in that scenario. This allows the system to be used in a configuration not unlike previous years when paper scoring was used. Of course the field still needs to be randomized, but we felt it would be more of a burden when trying to run the software in this minimal set up to force input every match.

**Comment by slacter** [comment]
Unfortunately, I have presented a use case where inaccurate scoring has occurred.  Could this be revisited?

**Comment by adwiii** [comment]
You will have to elaborate how the scoring was inaccurate and what about the scoring system behavior led to that inaccuracy. If live scoring was disabled then the randomization has no bearing on the scoring input to the scoring system.
