### ISSUE TITLE
Audience Display: Need capability to display custom message with countdown timer.

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#22]
Audience Display: Need capability to display custom message with countdown timer.

**Comment by adwiii** [comment]
As of 0.7.5 you can display a custom message from the Video Switch tab on the Match Control Page. This does not support a timer because we believe that the timers already implemented for field and alliance timeouts are sufficient. If a countdown timer of more than 5 minutes is needed, the message can be edited to say the time that you would countdown to. For example, instead of counting down to the end of lunch, the message could say "Matches will resume at 1pm".
