### ISSUE TITLE
Matchmaker generates the same schedule

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#221]
Matchmaker generates the same schedule no matter how many times you run it-this includes if you have two events with the same teams (e.g. league meets)

This behavior was observed on two separate machines using OS X.  It was observed using a real event DB-I also reproduced with the attached test DB.

I was able to temporarily resolve the issue by replacing the matchmaker executable with one from last season, which suggests the issue is with matchmaker and not the scoring system.

[test_event.db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2636274/test_event.db.zip)

**Comment by maths22** [comment]
I verified this on a copy of matchmaker downloaded direct from idleloop: for a given set of configuration settings, it always generated the same schedule.

Also used Wine to run the windows version, and the windows version is fine: each run generates a different schedule.

**Comment by tomsax** [comment]
There's a new build on idleloop.com that fixes the bug in the Mac version.

https://idleloop.com/matchmaker/download.php

There was a configuration error that caused the random function to be seeded with srand(time()) instead of the preferred srandomdev(). That used to work just fine, and does still work on Windows and Linux, but no longer works on macOS. The new Mac build uses the correct function and produces different schedules.

**Comment by maths22** [comment]
Resolved in v0.6.0
