### ISSUE TITLE
Pips on Audience Display vs Field Display are reversed

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#227]
This is very, very minor, but the OCD in me has come out.  On the Audience Display, when you choose Show Random, the Pips on the die are reverse from the Pips on the die of the Field Display. This can only be seen if a #2 or a #3 are "rolled", but they are different.

**Comment by emmell620** [comment]
More investigation.  The issue with the pips reversing is purely between the Field Display running on a laptop and the Audience Display running on a Raspberry Pi.  The pips are correct if they are using it going between two laptops.

**Comment by adwiii** [comment]
This *should* be resolve in v0.6.0. Read on for more details:
@emmell620 they are referencing the character for the die face ([in this family](https://www.fileformat.info/info/unicode/char/2680/index.htm)), and it appears to be an issue of the devices not having the same font. The system now ships with the referenced font, so this should be resolved. However, since it is system dependent, I cannot vouch that it is definitely fixed for the set up you observed. I am going to close this issue, but please re-open if you observe this behavior again in v0.6.0+
