### ISSUE TITLE
Add CORS to 3rd party API

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#231]
As a RO API, it should be safe to add CORS headers with a '*' origin to the API.  This will allow development of web-based tools that pull from the API.

**Comment by MichaelLeonffu** [comment]
Please.... this would be very useful; compared to the alternative of making an electron app.....

**Comment by CameronDeMille** [comment]
It would be super helpful to have CORS headers on the API. I would greatly appreciate being able to do CORS for my web app.

**Comment by cmacfarl** [comment]
I am not sure that I understand just what benefit CORS brings to our
community beyond the existing public API.   Please explain it like I'm 5.

**Comment by jvens** [comment]
I believe that CORS could be a significant value add for the community.

I can get into the technical details of what CORS is and how it works if you would like, but as a TL;DR it means that on modern browsers javascript running in a website on `foo.com` can't access any data from `bar.com` through AJAX calls without `bar.com` server giving explicit permission to `foo.com` using an HTTP header `Access-Control-Allow-Origin: foo.com`.  This HTTP header also supports the wildcard * which allows any origin which is what is being asked for in this issue.  This access to content on one domain (`bar.com` in this example) from another domain (`foo.com`) is Cross Origin Resource Sharing (CORS) and the reason that it is disabled by default is for security reasons.  In the case of the score system and the read-only API there are no security issues with allowing CORS.

So here is an example of an application that could make use of CORS.  Say TOA or ftcscores wanted to make uploading scores to their services not require any app running on the computer.  They could instead create an event upload page on their website (`ftcscores.com/upload` for sake up example) which the event opens on a computer that also has access to the score system network and the external internet.  The javascript on that web page would be able to use AJAX to make HTTP GET calls to the public API (say at `192.168.1.100`) and then upload that content to their servers (say `ftcscores.com`).  The problem with this is when they make that initial GET request to the score system the browser will consider the origin of the request to be `ftcscores.com` and since the request origin is `192.168.1.100` and the score system has not explicitly allowed requests from `ftcscores.com` to access the score system, the browser will not allow the request to complete.  Adding the CORS header would allow the request to complete and make uploading data to the third party service much easier.

Another example of something that can make use of this is a rankings ticker that I used at the Iowa Championship this weekend.  You can see it here: [YouTube](https://youtu.be/6Th8uUSo6Ns?t=1139).  To get around the CORS restriction I have to use a Chrome extension ([Moesif Orign CORS Changer](https://chrome.google.com/webstore/detail/moesif-orign-cors-changer/digfbfaphojjndkpccljibejjbppifbc?hl=en)) which is not very user friendly.

**Comment by CameronDeMille** [comment]
@jvens explain is perfect. Heres how enabling CORS would help my project in particular:

I have a website that displays live rankings, OPR, and match scores for events. Similar to TOA but with some differences. I need data from the scoring system during the event, so I make requests to the scoring system API. I make those requests through an application I made for windows/mac that will upload data from the scoring system API to my private API. 

The problem here is that if I want other FTC events to upload their data to my private API they have to download and run my application. It would be more convenient if I could send them a link to a web page that they can have open instead of a separate desktop application. As of right now since CORS is not enabled by the scoring system API, I can't make a page on my website to handle the data upload to my API. It has to go through a separate application that operates on the same network as the scoring system.

**Comment by adwiii** [comment]
This has been added in v1.1.0

**Comment by jvens** [comment]
This feature is still not working.  I used the test file linked to above in the gist and this is the output in the chrome web console:

```
test.html:14 Access to XMLHttpRequest at 'http://localhost/api/v1/events' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by ofekashery** [comment]
@jvens CORS doesn't work in ``file://``.
Try to serve your app on localhost (using [http-server](https://www.npmjs.com/package/http-server) or something like this).

**Comment by jvens** [comment]
@ofekashery, yes it does.

But I just tested again and I realize what is wrong.  If I request `http://localhost/api/v1/events` it fails with that CORS warning because the server is actually responding with a `302` error that does not have the CORS header.  When I request `http://localhost/api/v1/events/` with the trailing slash then it returns `200` and the CORS header is set correctly.  So the only problem was my missing the trailing slash.

**Comment by ofekashery** [comment]
Yes, I was wrong

@adwiii The problem is that you send us 302 to add ``/`` to the url without ``Access-Control-Allow-Origin``
@jvens It works if you use ``http://localhost/api/v1/events/``

**Comment by adwiii** [comment]
Yes, the redirect happens before the CORS header gets added - the 302 is trying to redirect you to the URL with the trailing slash, and that URL will have the CORS header. If the lack of CORS is preventing you from following the redirect then I guess we could add it before the redirect, but that seems silly.

**Comment by jvens** [comment]
@adwiii, my opinion is the way it is working right now is probably fine.  All the API requests should be made with the trailing slash anyway to avoid redirects all the time.
