### ISSUE TITLE
Interpretation of browser tab/page recommendation.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#232]
This is an operations question rather than an issue.
I'm just reading the manual in detail, and I came across this recommendation:

> It is recommended that the Match Control Page be used in full screen mode, and that the user not navigate away from the Match Control Page’s browser tab. If the user would like to have two or more active browser screens on their laptop (for example, if the user wanted to display the match control page and the field display page), it is recommended that user have two separate browser windows (and not two browser tabs within the same window) launched on their computer.

Since this is just a recommendation vs a requirement, what are the likely impacts of not following the recommendation.  What issues would I expect to see?

Will the system be unstable, or is this just based on reducing the testing requirements?   

If there are actual concerns about using multiple tabs, shouldn't this be a hard requirement, rather than a recommendation?

**Comment by adwiii** [comment]
As far as the system is concerned a tab and a browser window are no different. The key here is that you want to make sure you do not lose track of any Match Control Page, Display, or Referee Page because having too many of them open can lead to unpredictable results. We have had issues in the past where a Display would be opened in a new tab and then forgotten about and that causes problems later on. We felt that a browser window was easier to keep up with than a browser tab. As such, this is truly a recommendation - it is acceptable to run in either two tabs or two browser windows, but it is safest/easiest to keep up with in separate windows.

As for using the Match Control Page in full screen - same thing, just something to maximize focus and minimize chance for error by taking user focus away, the system is fine with either.

**Comment by gearsincorg** [comment]
Cool.  Thanks for the clarification.
