### ISSUE TITLE
Referee undo pre-match settings

### ISSUE THREAD

**Issue by vwestin** [FIRST-Tech-Challenge/scorekeeper#234]
We have had a few matches where the referee would make their pre-games selections (robots latched) and moved on in the app. However, if they make a mistake, they have no way to go back and correct it. It would be nice if they had a button to go back and update this before the match starts.

Also, we had one match where even though the referee tablet was ready to score live gameplay, the scoring system indicated that they were not ready. We have seen this a few times, and forced the game to start anyway. Normally, the game is played and we adjust any score details at the end if the tablet issues continue. However, for this one match (we have not been able to recreate it), the match did NOT start correctly. The timer was running and we had the audio feedback, but there was no 'abort match' button (we still had the red 'start game' button, which did nothing). So will killed off the scorekeeping app and restarted it. The app resumed the game in play (timer counting down), but it froze at 0:01 (1 second remaining). While we were waiting, and after the clock got to 0:10, the same red 'start game' button had no effect. We killed the app and restarted it again, and that allowed us to play the match for real. On software restart, it would be good to force an 'abort game' button of the countdown is still running.

**Comment by adwiii** [comment]
I agree that there needs to be a way to go back to the pre-match setup. That is something I have on the docket to fix.

The scenario you describe will take some thought as to what could have caused that. Can you describe the physical setup? Were the Display and Match Control pages both running on the same computer in the same browser?

**Comment by adwiii** [comment]
Although it is not as big of a deal this year with no robot pre-match setup other than no show, this operation is now supported. 
## Pre-Match
From the pre-match waiting screen, there is now a button to go back to the pre-match setup page. The page now also displays which teams have been marked as a no show.
![image](https://user-images.githubusercontent.com/9453262/64703435-6a896a80-d47a-11e9-9ae1-0ec0d90f3c28.png)

## During Autonomous
This button is also available at the top of the autonomous page. This exists because when the scorekeeper starts the match, the score tracking page immediately leaves the pre-match page without confirmation from the referee. Thus if the referee was trying to get back to the pre-match setup page when the match starts, they can still do so:
![image](https://user-images.githubusercontent.com/9453262/64703570-b9370480-d47a-11e9-9075-b29c97df605b.png)

This is ***not*** available during Driver-Controlled.

**Comment by adwiii** [comment]
To clarify, the Referee has the option to go back to Pre-Match Setup until they submit their Autonomous scores. The actual timing of the match does not matter.
