### ISSUE TITLE
SF 2 Teams all return -1

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#239]
`http://localhost/apiv1/events/ket/elim/sf/2/` returns 
```json
{
    "matchList": [
        {
            "match": "SF2-1",
            "red": {
                "seed": 2,
                "captain": -1,
                "pick1": -1,
                "pick2": -1
            },
            "blue": {
                "seed": 3,
                "captain": -1,
                "pick1": -1,
                "pick2": -1
            }
        },
        {
            "match": "SF2-2",
            "red": {
                "seed": 2,
                "captain": -1,
                "pick1": -1,
                "pick2": -1
            },
            "blue": {
                "seed": 3,
                "captain": -1,
                "pick1": -1,
                "pick2": -1
            }
        }
    ]
}
```

**Comment by Techno11** [comment]
Here is the .db 
[ket.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2660122/ket.zip)

**Comment by cmacfarl** [comment]
Are you doing paper or live scoring

**Comment by Techno11** [comment]
Ah.  So the live scoring tablets for field 2 were not working, while field 1's tablets were working.  Would that be why?

**Comment by Techno11** [comment]
So we were doing paper for field 2, and live for field 1

**Comment by adwiii** [comment]
Yes, and when the scorekeeper entered the data from paper on field 2, they did not select a team as no show. That would cause what is seen here.

**Comment by Techno11** [comment]
Ok. So is that a bug?

**Comment by adwiii** [comment]
Right now the scoring system does not require the scorekeeper to enter which team did not play because that information is not used later (ie, it doesn't matter for determining the winner of the match and is not displayed to the audience). However, since the data is exposed by the API, it is something that we would like to collect. Until the software is changed, the scorekeeper needs to know to enter which team did not play as a no show. We are investigating alternative ways to go about this to make it easier/more intuitive for the scorekeeper.

**Comment by adwiii** [comment]
As of 0.7.5, the system now requires the user to select a team to mark as a No Show during 3 team eliminations so that this information is always reconstructable.
