### ISSUE TITLE
Head Referee view

### ISSUE THREAD

**Issue by jkelbick** [FIRST-Tech-Challenge/scorekeeper#242]
We need a head referee account which allows the head referee to view and edit the details of previous matches, penalties, cards, etc. without involving the scoring table. This should include a scoresheet view to help answer question box questions.

**Comment by adwiii** [comment]
Is this targeting a tablet like the score trackers are using? If the head referee is logged in with the same permissions as the scorekeeper, they can access the scoresheets of the match in a semi-tablet friendly way (Go to Match Results, then select Scoresheet to see both red and blue alliance on the same page, or view one alliance at a time with Red or Blue). Below you can see what the page looks like on my Amazon Fire HD 8, you can see that scrolling down would show the Blue Alliance

I am hesitant to make a page that is formatted for mobile viewing that can change all of the scoring inputs because of the sheer volume of inputs. There would be over 75 user inputs on that page, and I would be very concerned about accidentally changing more than expected, or the page being so long it is unusable. For now, editing should be done at the scoring table.

Scoresheet on a tablet:
![image](https://user-images.githubusercontent.com/9453262/49738204-c9f0ea80-fc5c-11e8-94e2-b99f6c2b83e7.png)

**Comment by jkelbick** [comment]
Yes, the targeted device would be a table or mobile phone. I do not need to be able to edit multiple matches on the same screen, but I would like to be able to edit one match at a time from the head ref views. The main distinction I can see between head ref views and a scorekeeper view is that the scorekeeper would likely have access to additional functions (generate match schedule, etc.) that a head ref wouldn't need. That being said, until we have a head referee mode, I have been logging myself in as a scorekeeper.

**Comment by jkelbick** [comment]
@adwiii I'm playing more with the software on my own right now, and the scorekeeper's Active Match/Score Edit view might be nearly perfect, assuming the ref's screen size is sufficient. The only thing I'd like a head referee to be able to do in addition to this is enter notes on individual teams.

**Comment by erikorlowski** [comment]
Another thing that would be very nice would be to have an in-match view for head referees, similar to what's available for head referees in FRC. Here is what I'm envisioning:

Pre Match:
- Show when scoring referees have marked that they are ready for the match.
- Randomize the field and/or show randomization status of the field.

Autonomous:
- Ability to view penalties inputted by other referees.
- Ability to inputs penalties for either alliance.
- Ability to add cards for teams.
- Ability to see when scoring referees have submitted autonomous scores.

Driver Controlled:
- Ability to view penalties inputted by other referees.
- Ability to inputs penalties for either alliance.
- Ability to add cards for teams.
- Ability to see when scoring referees have submitted driver controlled scores.

Post Match:
- Ability to view penalties inputted by other referees.
- Ability to inputs penalties for either alliance.
- Ability to add cards for teams.
- Ability to see when scoring referees have submitted final scores.
- Ability to communicate to scorekeeper that match score is complete and ready to be displayed.

Eliminations:
- Show 5 minute timer for <T14> for each playoff series (i.e. SF1, SF2, finals)
- Show if alliances have timeouts available
- Show timeout timer
- Show time remaining to call timeout per <T15> and submit lineups per Game Manual Part 1, 5.10.

**Comment by jkelbick** [comment]
Have any of these features been included in the Skystone version of the FTC software?

**Comment by adwiii** [comment]
No head referee improvements have been added in v1.0.0. We will continue to evaluate this issue moving forward. HR improvements are something I would like to add long term, we simply did not have time to get to it for v1.0.0.

**Comment by jkelbick** [comment]
@adwiii As long as it's on the list for this season, I'm happy!

**Comment by adwiii** [comment]
The Head Referee page added in `v3.3.7` addresses many of the above concerns other than the Head Referee being able to edit the scores directly from their page. Please see the release notes and internal feature documentation for more information.
