### ISSUE TITLE
Pre-Match Setup

### ISSUE THREAD

**Issue by jkelbick** [FIRST-Tech-Challenge/scorekeeper#243]
After a match, there is no way to view or revise the pre-match setup inputs from a referee.

**Comment by adwiii** [comment]
There is no way for the scoretracker to change this, yes. If a referee has incorrectly marked someone as a no show, then this can be corrected at the scoring table. As discussed in #234 I am working on a way to move backward in the flow so that before the match has started the referee could correct this earlier on. However, I am hesitant to allow the scoretracker to edit this on the review page because of the unintended consequences it could have with being consistent on trying to validate the input on the scoretracker pages. I suppose if marking a team as a no show invalidates a selection later on, the UI could highlight it such as in #200 to flag it as invalid and then it would be the scoretracker's responsibility to rectify the situation before submitting.

Do you mean just changing no show, or also changing the initial latched status? If the latter, is it solely so that the scoretracker has the ability to add the landing that they missed in auto?

**Comment by jkelbick** [comment]
I haven't had to mark anyone as a no-show yet, but that sounds important too. Yes, I'm referring to the ability to change someone's latched status. If they're not marked as latched before the match starts, the referee cannot say they landed in autonomous. I do not understand the rationale for not exposing these options to anyone once they've been initially submitted.

**Comment by pmichaud** [comment]
Just to +1 this issue; at our event yesterday we had a referee in semi-finals that accidentally hit "Alliance Ready" before marking the two robots as being latched, and no way to correct this.  Although the final score can indeed be corrected after the match, it significantly affects live scoring, so we felt a need to inform the teams that the live scoring display would not have the correct landing totals displayed and to play accordingly.

Pm

**Comment by adwiii** [comment]
As commented in #234, referees can now revert to the pre-match setup page before the match has started and during the Autonomous period (meaning before they have submitted Autonomous, not when the timer runs out). This is our preferred solution to this issue as well - the referee should have ample time to correct the any incorrect no shows and the issue should be evident during Autonomous because the page will prevent them from entering scoring information.
