### ISSUE TITLE
Ability to import awards

### ISSUE THREAD

**Issue by slacter** [FIRST-Tech-Challenge/scorekeeper#254]
_Originally posted by @mglennon in https://github.com/FIRST-Tech-Challenge/scorekeeper/issues/222#issuecomment-445506719_

**Comment by rgutentag** [comment]
I would like to see this also

**Comment by adwiii** [comment]
This was added in v2.3.0. Awards can now be transferred:
* Online -> Traditional (file import or direct sync)
* Traditional -> Traditional (file import)
* Traditional -> Online (on final event upload)

## Hybrid Events
Hybrid events are those that do remote judging but in person matches. If you run a Hybrid event and use the Online Scoring System to enter awards, they ***MUST*** be imported into the Traditional Scoring System that is used to run matches - this does not happen automatically on event setup. When the matches are completed and the event is uploaded from the Traditional Scoring System to *FIRST* the awards that are present in that event will *overwrite* any awards that are in the Online Scoring System. In order to ensure that the awards are correct, follow one of the steps below to transfer the data from Online to Traditional.

## Syncing directly with the Online Scoring System
If you have an internet connection and have configured your event properly through the Online Scoring System, you can directly sync the awards from the Online Scoring System. From the Traditional Scoring System, on the awards entry page select the "Import/Export" tab. Then select "Sync From Online Scoring System". This will directly pull the awards information from Online -> Traditional.

## Exporting a file from Online
From the Online Scoring System, ftc-scoring, on the awards entry page select the "Export Awards" tab. This will download a `json` file. This can be used to import from Online -> Traditional
![image](https://user-images.githubusercontent.com/9453262/108929471-1e040180-7612-11eb-86d8-648479f53c72.png)

## Importing a file into the Traditional Scoring System 
From the Traditional Scoring System, on the awards entry page select the "Import/Export" tab. Then select the "Browse" option and select the downloaded file. Then use the "Import Awards" button. This can be used to import both Online -> Traditional and Traditional -> Traditional
![image](https://user-images.githubusercontent.com/9453262/108929682-7e933e80-7612-11eb-9252-95ca85674e1b.png)

## Exporting from Traditional
From the Traditional Scoring System, on the awards entry page select the "Import/Export" tab. Then select "Export Awards". This will download a file that can be imported into another copy of the Traditional Scoring System. The use case for this is the closest to the original request. If judges are in an isolated part of the building that has no network access, they can run another copy of the Traditional Scoring System, add the awards they need, and then export those awards to be imported back into the main copy of the scoring system running the matches, etc. To set this up
1. Set up the "main" copy of the Scoring System that will be running matches and will be used to submit data to *FIRST*. Ensure that all teams that will participate in the event are added to the team list before proceeding.
2. On the Event Dashboard, select "Download Archive File".
3. Transfer the downloaded `db` file to the computer that will run the Judges' copy of the Traditional Scoring System
4. From the Judges' copy, once logged in as an Event Admin or higher, navigate to the "Event Admin" > "Manage Server" dropdown option to get to the Server Management page.
5. Under the "Data Import" section, upload and import the `db` file from step 3.
6. Judges add all of the award information into the Judges' copy of the Scoring System
7. On the Judges' copy of the Scoring System, navigate to the awards page, then the "Import/Export" tab, and select "Export Awards".
8. Transfer the downloaded `json` file to the computer running the "main" copy of the Scoring System.
9. On the main copy's awards page, on the "Import/Export" tab, use the file upload to import the `json` file.
10. Verify that the awards were imported properly. There are a few safeguards in place, but certain error conditions can occur that would prevent the awards from importing properly.

 ***NOTE:*** With the v2.3.0 update, the "main" copy of the Scoring System will relay data to ftc-events.firstinspires.org throughout the event. It is very important to follow the steps outlined above to set up the Judges' copy of the scoring system as this will ensure that the Judges' copy does not try to upload data. *Having two copies of the Scoring System uploading data at once will lead to undefined behavior*. Awards data is not part of the automatic upload and is only uploaded to ftc-events.firstinspires.org when the "Send Results to *FIRST*" portion on the event dashboard is completed. 



CC: @mglennon as the original reporter
