### ISSUE TITLE
Combined rankings do not show before first match in 0.6.1

### ISSUE THREAD

**Issue by tcflanag** [FIRST-Tech-Challenge/scorekeeper#261]
When I create a league tournament, and import my previous league data, the rankings page is now empty in 0.6.1.  0.6.0 would show the rankings based on the imported data,

![image](https://user-images.githubusercontent.com/24835710/50265258-a142c080-03d3-11e9-8a88-7796e6f298a5.png)
[test_lqt.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2697501/test_lqt.zip)

And the same actions done in 0.6.0:
![image](https://user-images.githubusercontent.com/24835710/50265344-0991a200-03d4-11e9-9a14-b5f4ce615de6.png)
[lqt_test_060.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2697504/lqt_test_060.zip)

Once you enter scores the rankings seem to update as expected however.

**Comment by khoyt5** [comment]
Same problem in 0.7.0

**Comment by adwiii** [comment]
This happened because the system does not show a team in the ranking if they are not present at the event, but rankings did not re-calculate to show the teams until after the first match had played. 

As of 0.7.1, the rankings are updated as soon as a team has been added to the event. Once all teams have been added, you can view the corrected rankings (though you may have to allow a moment for the rankings calculation to finish if you are quickly swapping between screens - rankings can be slow given the number of matches in a league history).
