### ISSUE TITLE
Using SMART TV's - webOS as the interface

### ISSUE THREAD

**Issue by wehrenberg** [FIRST-Tech-Challenge/scorekeeper#267]
I've been using the FTC Scorekeeper V7.0 with an LG webOS TV as the browser. At first, it appeared that the browser would work fantastic as both a large screen display and wireless connection to the FTC 7.0 Scorekeeper server. But when I finally tested the LG TV on the Scoring/Field Display page, the setup page would not "Save" or "Cancel" and would simply hang on that window. In other words, I could not set the field to display, the display mode, test the audio and so on. The webOS browser would "hang". I could go back a page and look at other pages but as soon as I went to a screen (like Scoring/Field Display or Match Control page) where there were interactive browser buttons to select, the LG TV browser would not interact with the server properly. My quick thought is, even the webOS supports JAVA, that there is some sort of limitation in the webOS or some sort of "server-based" JAVA script or "browser-based" JAVA script issue. It would be interesting to get a developer's comment on this implementation to potentially help FTC events use fewer computers and take advantage of SMART TV systems. On a related note, my quick thought is that webOS is the best OS for SMART TV's to use this configuration.

**Comment by wehrenberg** [comment]
One additional troubleshooting comment - I should mention that the signon page to access all the screens of the ScoreKeeper system worked fine with a valid ID and password. In other words, that interaction with the LG webOS TV worked fine when entering the data and hitting the "Login" button. So there is something unique to the Scoring/Field Display and Match Control pages in terms of onscreen interaction with the user. ------I highlight this topic so much as a notable tool to minimize hardware and cabling for FTC events. On Feb 2 is our inaugural FTC event in TN and I have to make several thousand dollars in purchases and working to minimize the money, the amount and kinds of hardware, and minimizing the cable install are all good goals.

**Comment by tvbarnette999** [comment]
Is there a setting to enable javascript?

The display is very different from most other pages. It relies much more heavily on javascript, while the login page has virtually none. A good test might be to pull up the pit display and see if the scrolling works. Or, pull up the display like you have been, then on a computer, load a match on the control page and show the match preview. The display should still show the preview behind the options popup. If neither of these work, then javascript is not running at all. If they do, then its likely a problem with the user input mechanisms. If this is the case, you can bypass the user interface part of the display by typing in the full URL of the display. If you open the display on a computer and click save, you'll notice the URL changes. If you type out what you see then on the TV (changing localhost to the server IP if applicable), it should bypass the popup. From there, you could test to see if all the various functionality of that page works (timing, updates, live scoring).

I can see the use for smart TVs in this capacity, especially since TVs are already often used for field displays. My concern with them is partially the TV and partially the wireless aspect of it. We have developed the displays with the assumption they will always run on a browser with a somewhat modern featureset. Smart TVs are less likely to meet this assumption. Wireless is also more likely to introduce latency into timing due to noisy environments and distance, which is why we recommend wired connection to all timers. 

From a practical standpoint, we cannot test it on smart tvs, and thus cannot guarantee they fully support everything needed. Event day support would not be able to provide much help if anything went wrong. The safer approach is to get a Raspberry Pi ($35) or similar and tape it to the back of the TV.

**Comment by wehrenberg** [comment]
Scrolling does work on the pit display but I haven’t found a setting on the LG TV browser that helps with the Field/Scoring Display. I just can’t seem to figure out a way to answer the Field/Scoring setup screen settings and save them to the server. As for the TV’s browser environment, the settings for the browser are very simple with only four or five settings, none of which enable or disable JAVA….just things like “private browsing” Y/N, clear browsing history, and so on.

 

So it’s “close” on the webOS LG TV browser but missing something as the demands get a bit more complex (like on the Field/Scoring Display). I just wondered if there was a quick checkbox or “file inclusion” that provided formal support for any of the smart TV browser environments. The idea being that a simple “check the box” and recompile could then support some of the smart TV browser environments. I’ll keep trying some of your suggestions and actually have a chance to try a Panasonic smart TV this weekend to see if their environment (based on Firefox) has any better (or worse) luck.

 

I’m lucky enough to have a dedicated 5GHz router system that is unconnected to the internet and will be isolated to only the Scorekeeper system. So I’m not too worried about the wireless connectivity. That being said, I understand your comments about the architecture to properly run the system and just wanted to check on if the software environment had a simple way to simply include a “smart TV” environment. I also appreciate the timely response, advice, and direction. I’ll do some of your suggestions below and we’ll figure out a good path and go from there. Thanks and hope Christmas was good and that New Year’s will be!

 

Mike Wehrenberg

TNFIRST Nonprofit to promote K12 STEM programs

https://tnfirst.org <https://tnfirst.org/>  

1074 Scenic Dr

Knoxville TN 37919

865 389 9914 cell

 

TN-First-logo - High Quality - Grey - Small

**Comment by wehrenberg** [comment]
To close this idea of a direct link to SMART TV’s, at least for now, I’d say it’s a “no go”. I tried the Panasonic with absolutely no luck and the LG webOS, while close with some JAVA compatibility, only works with the Pit Display properly. The Field/Audience display simply does not track the server even when a match is running to “force” the TV to update. So, I found some free notebooks to front-end the large screen TV’s and we’re good to go. Thanks for diving in a bit as it could be a good way to save some hardware and cabling expenses (and ease the installation a bit too).

 

On a somewhat unrelated note, I see that selecting “Field 1” or “Field 2” in the setup of the Scoring/Timing Displays doesn’t really do anything in terms of a “2 Field” match setup. Am I missing something? The Scoring/Timing displays do cycle through Field 1 and Field 2 as you go through the match schedule; but, there really isn’t a “dedicated” Field 1 or Field 2 Scoring/Timing Display. Just thought I’d check to make sure that a “rookie” (me) isn’t missing something as build and operate this system.

 

Mike Wehrenberg

TNFIRST Nonprofit to promote K12 STEM programs

https://tnfirst.org <https://tnfirst.org/>  

1074 Scenic Dr

Knoxville TN 37919

865 389 9914 cell

 

TN-First-logo - High Quality - Grey - Small

**Comment by adwiii** [comment]
We did some additional testing on this and found some workarounds that at least got the display to load. However, after that point there were numerous problems with things such as the field sounds, etc. and the performance was not consistent. At this time we cannot recommend running the display on a smart tv, but maybe in future seasons with tvs becoming more advanced we can revisit.

I am closing this issue for now, as there is no clear future direction.

**Comment by wehrenberg** [comment]
Understood. I venture that the JAVA compatibility will get more main stream in the OS of smart TV’s. Especially as more and more online streaming and “online TV utilities” get developed. For now, I can drive two TV’s from one notebook with the extended desktop Windows utility and we’re good to go. Thanks for investigating and I’d still be a fan of a direct link to Smart TV’s, if and when the time is right.

 

Mike Wehrenberg

TNFIRST Nonprofit to promote K12 STEM programs

https://tnfirst.org <https://tnfirst.org/>  

1074 Scenic Dr

Knoxville TN 37919

865 389 9914 cell

 

TN-First-logo - High Quality - Grey - Small
