### ISSUE TITLE
Match 27 is counting twice

### ISSUE THREAD

**Issue by khoyt5** [FIRST-Tech-Challenge/scorekeeper#271]
Match 27 was aborted during the match and then replayed. The final score is in twice, one as 252-95 score and one as 252-0 score. This is occurring for all four teams that were in match 27.

![match27-twice](https://user-images.githubusercontent.com/14354979/50548998-ab5e8d80-0c23-11e9-8717-822f95dedbcc.png)
[sclm2.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2717289/sclm2.zip)

**Comment by tcflanag** [comment]
I'm seeing similar behavior on v1.1.2. I'm not sure of the exact day of event details, since I was not present. The extra match seems to fixed in the meet 2 rankings thankfully.

Meet 1 Match 1 is counted twice. 
[Columbia Basic Meet 1.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3992935/Columbia.Basic.Meet.1.zip)

[Columbia Basin Meet 2.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3992941/Columbia.Basin.Meet.2.zip)

**Comment by tvbarnette999** [comment]
@tcflanag As you mentioned, your league history is correct in future events, so you should be good moving forward importing this meet 2 db into future events. We know what's causing this problem and hope to have it fixed for the next release.
