### ISSUE TITLE
Deleted accounts not removed from database.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#290]
Testing 0.7.1

I can add and deleted user accounts, and the changes appear to be happening correctly.

But when I shut down the server, and restart it, the new user accounts are there, and so are the deleted ones.  Are the default accounts meant to be permanent?

**Comment by adwiii** [comment]
Hm. This is a side effect that I had not considered. As of 0.7.1, the server automatically detects if default accounts have been generated but any are not present and then adds those it is missing. The reason for this is that we added a new default account - lead inspector - and without any modification the new account would have shown up in the list even though it didn't actually exist in the server. 

There is a separate issue as well. Prior to 0.7.1, when you import an event into the server, if accounts had been generated prior to the import then they would show up as generated after import but would be non-functional because they had not been set up in the copy of the server it had been imported into.

To solve both of these issues, code was added that detects if accounts had been generated (There is a flag for this to show on the dashboard if it was done or not) and then checks to make sure all of the accounts are there.

So yes, if you generate default accounts, then every time you reboot the server they will all be added back. There is currently no way to "un-generate" default accounts.

Would the ability to "un-generate" default accounts suffice, or do you truly want to have only have a subset of the generated accounts exist?

**Comment by gearsincorg** [comment]
I'm still getting the hang of the way accounts work, and it seemed to me that I HAD to generate the default accounts to do anything.  But if that's not the case then as long as I avoid doing so, there is no problem.  I see I should just use the "local" account to create any non default accounts right off the bat.

I do think that if the default accounts are going to get put back in every time, then the option to delete them individually should be suppressed.   Having an "un-generate" for all of them would also have been helpful, but I'm not sure I would have been certain enough to use it.

Thanks.

**Comment by adwiii** [comment]
As of v1.0.0, generated accounts cannot be specifically deleted because they do not show up in the list of all accounts. In addition, generated accounts only work for the event that they were generated within. There is still no way to "un-generate" accounts, but these accounts can be re-randomized.
