### ISSUE TITLE
Is live scoring running on 2.4 GHz a problem without special action?

### ISSUE THREAD

**Issue by jdkunzeman** [FIRST-Tech-Challenge/scorekeeper#299]
The scorekeeper manual says "Wireless activity for the scoring system should operate on a Wi-Fi channel that will not interfere with the control of the competition robots."  I am getting ready to use live scoring and wireless connections for live scoring and field display for the first time.  When I set up the system without any attempt to change channels, my scoring system ended up running on channel 6 of the 2.4 GHz band.  It's very likely that in our competition with about 17 teams, some teams will also end up paired on that channel.  My question is, do I really need to do something about this for the competition?  I guess the options are to force teams to pair on a specific channel or try to get the scoring wireless system on the 5 GHz band, which at this point I don't know how to do.  For those that have been using live scoring, what has your experience been?

**Comment by jvens** [comment]
Speaking unofficially I can say I have never seen any issues from the score system interfering with the robots, especially for a small event with only 17 teams.  The wifi channel the score system is running on is controlled by the wifi router and not the actual score system.  If all of your tablets and remote displays support 5GHz then you can disable the 2.4GHz band in your router and run the entire system on 5GHz.

Personally I set up the score system router to use channel 1 and then I recommend the teams to use channels 6 or 11, but for any event with a reasonably clear wifi environment (i.e. not much venue wifi) and fewer than 20 teams I don't worry too much about what channels the teams are on and rarely see any ping times above a few milliseconds.

**Comment by Nate2019** [comment]
I agree with @jvens in that you shouldn't have any issues with only 17 teams. When I have to run an event on 2.4GHz though, I usually ask the event coordinators to not allow any teams or spectators on the venue wifi (if it's password protected) and to only allow volunteers to use it for event crucial things in order to eliminate interference. 

When possible though, I would recommend running on 5GHz as to leave 0 chance for the scoring tablets and system to interfere with robots, but all in all, you should haven't any issues with 17 teams + the scoring system on 2.4GHz.

**Comment by adwiii** [comment]
Closing as this discussion seems resolved. Feel free to reopen if there are additional questions.
