### ISSUE TITLE
high score

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#300]
It would be nice when the match score is posted to note if the score is the high for the day.  This when announced also gets a good cheer from the crowd.

**Comment by Nate2019** [comment]
This would be a great enhancement!

**Comment by adwiii** [comment]
The penalty total is included because that is fundamentally part of the score as defined by the Game Manual. While some people do want to know the high score without penalties, this is not within the scope of the scoring system. For the more philosophical nature of your question, I recommend starting a discussion on the FTC subreddit or discord, etc.


Closing as this issue has been resolved in 0.7.3.

**Comment by jkelbick** [comment]
Is it worth creating "Highest Score" and "Highest Score Without Penalties"
flags?
