### ISSUE TITLE
Problem with new colors in scoring overlay

### ISSUE THREAD

**Issue by cheer4ftc** [FIRST-Tech-Challenge/scorekeeper#309]
In a recent update, the timer bar in the scoring overlay was changed to show the time remaining over green for the first part of teleop, then over yellow during endgame, then over red when time expired.

The problem is that the scoring overlay is typically run through a green-screen filter to remove the green portion so the underlying video can come through in the background. With the new timer-bar colors, the timer also becomes greenscreened away, making it difficult-to-impossible to see the time remaining in the middle of the match before the end-game begins.

Please change the color behind the time-remaining bar to a different color that won't be confused with the greenscreen color.

**Comment by adwiii** [comment]
The color in the overlay by default is not an exact match to the timer bar color. The video software needs to be configured to have a low tolerance/similarity - you want it to perform an exact match on the overlay color (the default is `#00FF00`). See the discussion in #170 (specifically [this comment](https://github.com/FIRST-Tech-Challenge/scorekeeper/issues/170#issuecomment-436037537)), which I believe is substantially the same issue to this but for a different screen element.

You can also change the color of the overlay in the display settings:
![image](https://user-images.githubusercontent.com/9453262/51429827-ecbdd980-1be0-11e9-8cc0-69141587c3e2.png)
Which will produce a screen like this:
![image](https://user-images.githubusercontent.com/9453262/51429833-fc3d2280-1be0-11e9-93bc-980b3214a5b1.png)


If the software you are using is not easily configurable to perform an exact match, then hopefully you can find a color that works well to swap the overlay to. The magenta can be bad because a partial match filter then matches the red alliance color, so you may need to try several.

Closing because I believe this is addressed by #170 - we can re-open and continue discussion here if not. My concern is that we will not realistically be able to always guarantee that a range of colors do not appear on the screen given the number of things that are shown (I can guarantee nothing matching `#00FF00` exactly, but I cannot guarantee no "green"). Hopefully by giving the user the ability to change the color and also decreasing the tolerance on the video software, the user should have the tools to make the set up work for them.

**Comment by cheer4ftc** [comment]
Looks like we aren't the only region with this problem. Check out the time display on this stream from NEFIRST/FIRSTHQ.

https://www.twitch.tv/videos/373925485?t=10h17m45s

Sure you can't change that color from green (that is nearly universal for a screen color) to something else?
