### ISSUE TITLE
inputting awards into system

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#330]
I would like to see the judges role be activated so the JA can input the awards while matches are still being played.  As it is currently implemented the scorekeeper has to input the awards when they are not running a match.  There is a lot of down time when you have 2 fields.

**Comment by davewdavis3299** [comment]
There is a judgeadvisor role in at least 0.7.3 that already allows that. I used it two weeks ago for our League tournament and it worked like a champ
dave

**Comment by jvens** [comment]
You can achieve exactly what you ask for by logging in the judge adviser computer as the eventadmin account.  This is what I have been doing at my events and it allows the judges to enter awards while matches are still being played without interfering with the field or requiring the attention of the scorekeeper.  The only caveat that I make sure to let the JA know is not to press the `Present Awards` button since that will cause the audience display to switch to awards during the match.

**Comment by rgutentag** [comment]
jvens thanks for the work around.  I can use this till the developers decide if they want to create a function for the judge role.

**Comment by adwiii** [comment]
As of v1.0.0, the judge role can now input, but not present awards. See #205
