### ISSUE TITLE
Add option to associate timeout with the alliance

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#336]

**Comment by adwiii** [comment]
With the Head Referee feature introduced `v3.3.7`, the Head Referee now has the option to track which Alliances have used their time out in order to ensure that the same Alliance does not try to call two timeouts. Marking an Alliance as having used their timeout is *independent of the timeout starting*; the Head Referee must coordinate starting the timeout with the Scorekeeper. Please read the release notes and the internal documentation for more information on the new feature.
