### ISSUE TITLE
Dual Division Advancement Report

### ISSUE THREAD

**Issue by ggisme** [FIRST-Tech-Challenge/scorekeeper#343]
Click on the Advancement Report for a dual division event while in the Finals Event results in a file not found 404 error.

**Comment by tvbarnette999** [comment]
Could you upload your 3 databases in a zip? Which method did you use for division assignment?

**Comment by ggisme** [comment]
I used a custom sort method for division assignment. I basically just picked the teams I wanted in each division by checking the box in the teams page. I also ran with a single instance of the scoring software acting as the server.
[aml_champs.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2826550/aml_champs.zip)

**Comment by hightechkids** [comment]
Did you input your award winners into the finals event as well?  I'm running a dual division championship this weekend and would like to understand this.  I just took my database and input my 3 inspire finalist and then clicked on the advancement report and it printed what I had (namely the inspire winners).

**Comment by adwiii** [comment]
@ggisme did you add all the teams to the Inter-Division Finals event and then separately enter the teams for each division?

**Comment by ggisme** [comment]
@hightechkids yes, I entered in all the awards.
@adwiii yes, entered all teams into the finals event. Then selected the teams for each division from that list.

**Comment by adwiii** [comment]
@ggisme the issue has been resolved in v0.7.5 and we have added code to prevent this going forward. In your case, import the _0 event into 0.7.5 first and then import the _1 and _2 events. The reason this error occurred is that the _0 event did not have the division assignments. In versions prior to 0.7.5, if you added a team to the _0 event and then added the team to the _1 event directly (as opposed to assigning it to division 1 in the _0 event) then the _0 event would not update to know that it was in division 1. 

Let us know if you have any problems.

**Comment by hightechkids** [comment]
Excellent. Thank you for the analysis.  This should not be a problem for
us, since I imported the teams with division assignments already noted in
the excel spreadsheet.  Any changes I've made to teams (one advanced from
another state championship) I've made at the *_0 level, since that's where
we'll be assigning awards and running finals.  I plan to just use the *_1
and *_2 events to run qualifier and alliance matches up to the finals.
Makes sense to me.

Thanks for all your help!

Norm Tiedemann
FTC Program and Volunteer Coordinator
High Tech Kids - Minnesota
