### ISSUE TITLE
Suggestion: Make all achievements actively confirmed or denied in future seasons

### ISSUE THREAD

**Issue by cheer4ftc** [FIRST-Tech-Challenge/scorekeeper#351]
Many/most ref scoring errors occur because a scoring ref forgot to register one or more scoring achievements. This is because the default state of a scoring screen is every scoring achievement "not achieved". So it's easy for a ref to skip over things.

Scoring would be much more accurate if, for each achievement, the scoring ref had to enter an answer either way (e.g., "was scored" or "was not scored"), or "which way" in the case of a multi-state achievement, and then if the screen can't move from autonomous to teleop until all answers are entered for autonomous.  If the scoring software required full entry for each and every achievement, scoring would be MUCH more accurate. And this is even more important in the new world of live scoring as there is less double-checking of scoring and less time for verification (especially after autonomous).

**Comment by HDMScot** [comment]
I have some strong opinions with regard to this.

* Default should be NOT SCORED in all cases

* I would support the concept of requiring a score for each portion of the match, but it would require a change in the workflow and change in the screens...something that should be done NOT in a season. In the meantime...

* I FULLY support the concept of an audit being added to the process that is, or could be, independent of the main dashboard. This is basically what we're all doing anyway...comparing the "live score" with the paper version and then committing...but right now it's a disruptive process in that the scorekeeper/dashboard operator has to do it.

Right now, there HAS to be a "backup" version of the scores other than the live scores...because there continue to be many opportunities for errors to occur in both the software and the referee actions, but equally as important...and maybe even more important...is the allowance for challenges/questions post-match. How do you go back to review a challenge/question without a record?

**Comment by cheer4ftc** [comment]
First, I agree that this should not be done this season. This is a suggestion for next season (as noted in the issue title).

Second, I humbly suggest that default for each achievement should be "NOT ENTERED" and then the ref should have to enter either "SCORED" or "NOT SCORED" for all achievements in autonomous before moving to the next screen, to ensure that each achievement has been accurately and thoughtfully noted.

Third, your statement that there HAS to be a backup is not happening in practice now. For example, all Virginia events (including our state championship last weekend) were done only with livescoring. There was minimal double-checking or confirming of scores. As you might imagine, there were more than a few unscored achievements that happened.

FYI, I believe that head refs can pull up a summary of each match's results on a scoring tablet too, which I believe is how our refs were dealing with scoring questions in the question box.

Personally, I'd like to see both required achievement scoring or not scoring as noted, plus a 2nd ref per alliance also noting the scoring (on a paper summary sheet, or maybe even on a separate tablet?) and then having those scores be confirmed with each other before they are committed.

**Comment by jkelbick** [comment]
I fully support the concept of every single field starting with a NULL value and requiring a TRUE or FALSE entry. I'd suggest the referee get one error message, but after they get that error they can proceed onto the next screen without entering TRUE or FALSE to allow for situations when additional guidance may be needed after the match.

Discussions about the refereeing process should be posted in the FTC Referee Volunteer forums for the GDC to consider, as this system is only used by the scoring application software developers.

**Comment by deliana-d** [comment]
One thing to add here. Assuming the current game play progression of 8 seconds between the autonomous and driver-controlled portions of the match is continued next year, depending on the number of possible achievements in autonomous it may prove a burden for the scoring referees to enter them all before that window expires if the default for all is NULL/"not entered" instead of "not achieved."

I know when I was a scoring referee at an event this year there were times when I was still looking at the tablet and double-checking my entries for autonomous achievements while the game had already progressed into the driver-controlled period.

So while I can certainly see the argument that a default state of NULL/"not entered" with error messages if you try to continue may lead to more accurate autonomous scores, I could also see this causing Referees to miss part of the driver-controlled match play because of the additional time required to enter values in all fields.

The instructions in the Referee manual for the paper scoring sheets do say to write in a '0' value for all unscored fields, so something similar to that requirement might be a good addition, but the time required to enter it would need to be considered, unless FIRST were to go back to the old method of manually advancing the match from autonomous to driver-controlled.

**Comment by cheer4ftc** [comment]
I humbly submit that if there's time to enter all scoring achievements as "scored" then there's time to enter all scoring achievements as "unscored." And if there isn't time to do one, then there isn't time to do the other either. 

And these days, there are plenty of matches that have fully scored autonomous achievements for both alliances.

[I'd personally love to see a few extra seconds added to the gap between auto and teleop regardless, but that's a whole different conversation. :) ]

**Comment by adwiii** [comment]
As of v1.0.0, on the Match Control page, under the settings tab there is a checkbox for "Require Referee Active Confirmation". This is unchecked by default:
![image](https://user-images.githubusercontent.com/9453262/64707975-d58a6f80-d481-11e9-8457-50f936eb398a.png)

When checked, the system requires referees to actively confirm/deny every input. This only applies to matches that have not been loaded for play, so it is recommended to turn this setting on before doing anything else if you intend to use it. When selected the page will not prefill "None" or 0 for any fields except for penalties:
![image](https://user-images.githubusercontent.com/9453262/64708130-197d7480-d482-11e9-8957-1c06bb865814.png)
The referee will have to enter every field before being allowed to submit Autonomous scores and before being able to submit Final Scores. The referee can still transition from Driver-Controlled to Review with some scores not entered. For all counter fields (including Stones returned) the referee must hit the down or Undo button to make the counter go from blank to 0. If the referee hits the Returned or up button then it will go from blank to 1. If a robot is a no show, the referee does not need to enter none for that robot. Note that for the capstone this can be a bit tricky because placing the capstone then activates a second input that must also be filled out. Hitting yes for the capstone and then not entering the level of the capstone, even if it is 0, will result in a warning from the system and that state will not be preserved on page refresh.

Please open a new issue if you have any questions about this feature.
