### ISSUE TITLE
Version 0.7.7 lost elimination match schedule only option

### ISSUE THREAD

**Issue by emmell620** [FIRST-Tech-Challenge/scorekeeper#360]
During our finals, we went to print our elimination schedule for our queuers and the checkbox for printing only the eliminations matches was gone (it was there in 0.7.5 I believe).  We printed the bracket report for the queuers as a workaround.
![image](https://user-images.githubusercontent.com/12737153/53346727-39ca5500-38dd-11e9-83e9-224e42060905.png)

**Comment by adwiii** [comment]
The checkbox for elimination matches only is only on the Announcer report, and remains there in 0.7.7. The Match Schedule does not show the elimination schedule because that schedule is dynamic, and would need to be re-printed after every round. The bracket report as you used it is the intended solution for this problem.

**Comment by emmell620** [comment]
Okay.  Thanks for the explanation.
