### ISSUE TITLE
Match Control: Undo Alliance Selection

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#37]
It should be possible to undo/reset alliance selection, and to view qualification matches after elimination matches have started.

**Comment by adwiii** [comment]
This has been fixed in 0.7.5. Under the Settings tab in "Danger Zone" on the Match Control Page. It will delete all of alliance selection and any generated elims matches. No elims matches can be in the committed state for this to work.

Viewing qualification matches cannot be done on the Match Control Page once elims have started, but you can do so from the Match Results page.
