### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#386]
could you make it for the displays a popup for cameras so if you want to live stream a meet you could choose the camera instead of using obs studio and if not could show me how to get to work in obs studio.

**Comment by jvens** [comment]
I am not exactly sure what you are asking for, but if you are suggesting a way to underlay a video stream instead of or in addition to chroma key then my opinion is that is out of scope for the score system.

As for instructions on how to make it work in OBS studio, here is instructions I put together last year: https://docs.google.com/document/d/1pU0uXlrUX6gFdAqsRMcF0KScxF53M2M5fExVAEvuEyo/edit?usp=sharing.  They are out of date in a few areas because YouTube has made changes to their UI for setting up a live stream, but the OBS configuration parts should still be accurate.  If you run into network issues checkout the Troubleshooting section of this document: https://docs.google.com/document/d/1J5jOCktIlDoxqoMlpoiBLDLtRpCmJGJN2d0VkunTaVI/edit?usp=sharing 

If you have further questions about livestreaming using OBS studio and YouTube please don't hesitate to reach out to me and I am happy to help. ~Jeramie

**Comment by adwiii** [comment]
As @jvens says, this is beyond the scope of the scoring system given the availability of third-party software to fill this need. I am closing this issue, but feel free to continue to use it for follow-up questions @GamingWithaAlexYouTube.
