### ISSUE TITLE
Matches per team

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#394]
you can’t do more than 6 matches per team could you fix that

**Comment by jvens** [comment]
As per [Game Manual Part 1](https://www.firstinspires.org/sites/default/files/uploads/resource_library/ftc/game-manual-part-1.pdf) Rule <T30>:

> *&lt;T30&gt;* Teams competing in a Meet, League Tournament, Qualifying Tournament, and Championship
Tournament will compete in no fewer than 5 Qualification Matches, and no more than 6 Qualification Matches.

**Comment by GamingWithaAlexYouTube** [comment]
for practice how do I add more matches

**Comment by GamingWithaAlexYouTube** [comment]
> As per [Game Manual Part 1](https://www.firstinspires.org/sites/default/files/uploads/resource_library/ftc/game-manual-part-1.pdf) Rule :
> 
> > _<T30>_ Teams competing in a Meet, League Tournament, Qualifying Tournament, and Championship
> > Tournament will compete in no fewer than 5 Qualification Matches, and no more than 6 Qualification Matches.

**Comment by cmacfarl** [comment]
The number of matches that the scoring system will support has been discussed internally.  The decision has been that the scoring system will enforce the rule within the game manual in this regard.

**Comment by GamingWithaAlexYouTube** [comment]
Last year you could do more matches

**Comment by jvens** [comment]
@GamingWithaAlexYouTube, you can always create as many test matches as you want from the `Settings` tab of the `Match Control Page`.

**Comment by adwiii** [comment]
The limit on matches was removed for the off season release over the summer. The limit will remain in during the season as @cmacfarl said. As @jvens said, I recommend creating multiple test matches or even multiple test events.

**Comment by gearsincorg** [comment]
The season is officially over.  
Can we have this 6 match limit removed now so we can start planning the larger than normal off-season competitions that will occur once the emergency is over?

**Comment by cmacfarl** [comment]
The official word from FIRST headquarters is that the season is _suspended_.  Until that changes it's not appropriate to modify the match limit.

**Comment by gearsincorg** [comment]
That's unfortunate.

Removing the 6 match limit will hurt no-one, but keeping it in place will mean that venues running multi-day makeup-events will not be able to use live scoring. (eg: MTI in MD).  

Given the total disruption of the season, and the efforts that these venues will be committing to keep the momentum going, it seems like such a small compromise might not be so inappropriate.

Also given the circumstances, it seems almost draconian to keep it in place.   "No MTI, you cannot use the scoring system if you intend to illegally offer teams more than 6 matches over 2 days."

I know, I know... the rules say so.  But strictly speaking <T30> only applies to "Meet, League Tournament, Qualifying Tournament, and Championship" which is not the case here.  Since off-season, non advancement events aren't any of the above, we get back to exclusion being somewhat draconian.  

Perhaps the development team could revisit this particular decision, given the positive effect this small accomodation could now have.

**Comment by emmell620** [comment]
Phil: I agree with you about lifting the restrictions. However, this is a call from FIRST HQ, and not the developers. I suggest you appeal to NH.

**Comment by gearsincorg** [comment]
Too bad.  
Seems like they have more than enough to be dealing with right now.
I'll wait and try to find a reasonable opportunity to ask.
Thanks.
