### ISSUE TITLE
Inconsistencies in the API Routes

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#396]
A few endpoints are inconsistent to the API Docs.  For instance
`/api/v1/keywait/` returns 404 while `/api/v1/keywait` returns correctly. (note the last `/` does matter)

This is different from `/api/v1/keyrequest` which returns 404 while `/api/v1/keyrequest/` returns correctly. Haven't tested all the endpoints, just thought this was an interesting one.

**Comment by GamingWithaAlexYouTube** [comment]
what does the API do

**Comment by cmacfarl** [comment]
@GamingWithaAlexYouTube [API Documentation](https://github.com/FIRST-Tech-Challenge/scorekeeper/wiki/API-Documentation)

**Comment by cmacfarl** [comment]
@Techno11 Can you please post the entire url that you are using that claims keywait returns 404 with the slash?  e.g.  Here's my result on that query.  Note that all of the routes have been set up within the system to require the trailing slash, so keyrequest is functioning as expected.  The issue here would be with that you seeing with keywait.

```
$ curl -s -X GET "http://localhost/api/v1/keywait/" -H  "Authorization: iqnsxazsXgWsuexIkRnTjlVcDHdRlQUf"
{"active":true}
```

**Comment by adwiii** [comment]
@Techno11 The keywait URL will return 404 if you attempt to wait for a key that does not exist. I cannot replicate the issue you describe - could it be a non-existent key or malformed authorization header?

**Comment by Techno11** [comment]
It's probably just an issue with my testing. I'll reopen if I encounter this problem again.
