### ISSUE TITLE
scheduledTime returning -1 for unplayed matches?

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#397]
Am I missing something here?  Is there a state that the scoring system has to be in in order for it to return the proper a timestamp? GETing `api/v1/events/test/matches/3` returns this:
```
{
"matchBrief": {
        "matchName": "Q3",
        "matchNumber": 3,
        "field": 1,
        "red": {
             ...
        },
        "blue": {
             ...
        },
        "finished": false,
        "matchState": "UNPLAYED",
        "time": 1569455236803
    },
    "startTime": -1,
    "scheduledTime": -1,
    "resultPostedTime": -1,
.....
}
```
How can I get a proper timestamp to return for `startTime`?  Thanks!
Update: The `scheduledTime` in the details endpoint also returns `-1`

**Comment by adwiii** [comment]
`startTime` is the actual time the match was started. The match says it is unplayed, so the time is -1 because the match has not been started yet.

`scheduledTime` is "hidden" by default - the user must uncheck the "Keep Schedule Private" checkbox on the Create Match Schedule page. This can be unchecked at any time and will take effect immediately:


![image](https://user-images.githubusercontent.com/9453262/65649176-76754080-dfd3-11e9-96d0-8e482470ad8a.png)

**Comment by Techno11** [comment]
My bad. Thanks for pointing this out!
