### ISSUE TITLE
V1.1.0 does not have the ability to load a sponsor's logo. Just name and "region/event". There is no way to add a picture file.

### ISSUE THREAD

**Issue by hightechkids** [FIRST-Tech-Challenge/scorekeeper#413]
![SponsorInputV1 1 0](https://user-images.githubusercontent.com/44174505/66661700-0c80ac00-ec0d-11e9-97b4-68e7f398910a.jpg)

**Comment by adwiii** [comment]
This feature has been removed for the foreseeable future, Sorry for the inconvenience.

**Comment by emmell620** [comment]
Why?  Is this a technical limitation or was this a request from HQ? Our sponsors liked seeing their names and logos on the scoreboard. Now, we're going to have to integrate in a PowerPoint deck to accompany the screens.

**Comment by hightechkids** [comment]
And integrating a powerpoint show might mean that the Global Sponsors don't get as much play time.

**Comment by JoAnnHalloran** [comment]
We're hopeful that we'll have an alternative to this. As I understand it, this was removed at the request of either our development or marketing team due to a concern about relative logo size (presenting sponsor logos were sometimes smaller than local sponsor logos). We'll keep you updated with a status on this. We understand the value in recognizing sponsors, and we'll work to come up with a resolution that works for us all. I'm sorry about the surprise, and the inconvenience!

**Comment by adwiii** [comment]
Sponsor logos can be imported into the system, but do have a maximum size and are displayed 4 at a time on the display. Region and event sponsors set up on [the online scoring system](https://ftc-scoring.firstinspires.org) will be imported with the event when it is imported into FTCLive. Sponsors, including their logo, can also be imported from one event into another by importing the database as part of the sponsor workflow.
