### ISSUE TITLE
How often will updates be released?

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#414]
From the release page for v1.1.0

> In addition, now that we are releasing less frequently...

How often can we expect releases this season, and will there be a certain day of the week that they will come out like last year?  This information would be useful for knowing how far in advance of a meet we can create the scorekeeper event.

**Comment by ftctechnh** [comment]
@jvens 
Hi Jeramie - as we did last year, for longer term scheduled releases we are targeting a Tuesday release on this repository.  However, the development team reserves the right to issue a critical fix release at any time during the week. 

We are trying to limit the number of releases of the software for this season, but the frequency will depend on how many issues are reported with the software.  Ideally, we'd like to have one long term scheduled release per month.

Also, with respect to creating an event in advance within the FTC Live software, FIRST recommends that you wait and create the event in the software closer to the actual scheduled competition date.  

When you are getting ready for an upcoming event, FIRST recommends that you connect your scorekeeping laptop to the Internet and use the "Data Download" function of the Manage Server page of the FTC Live server to refresh the local team list data before you create your event.

Doing this closer to your event date ensures that you have more current team information.  This is important because a Data Download refresh only applies to events created after the refresh.  

As an example, if you create your event on Monday, and then you download the updated Team list on Friday, the updated Team list changes will not be applied to your existing event.
