### ISSUE TITLE
Rankings on Match Preview not using combined rankings at league meet

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#442]
The rankings on the match preview display among other displays seems to show rankings for "this event only" instead of the combined rankings at league meets.  The screenshots below show the rankings from `/event/lothal_2019_10_25_meet2/rankings/combined/` and what is displayed at `/event/lothal_2019_10_25_meet2/display/config/ad/false/ad/ad/false/0/00ff00/true/false/false/false/classic/false/`

![image](https://user-images.githubusercontent.com/7074504/68217258-ef3ec380-ffa7-11e9-9627-6a83263fa2ed.png)

![image](https://user-images.githubusercontent.com/7074504/68217296-fbc31c00-ffa7-11e9-8a7e-c0b0b897b0d6.png)

You can see that team 6297 should be ranked 6, but instead says rank NP.

**Comment by adwiii** [comment]
I am not saying we cannot make this change, but I would like to make a few comments.
This has been the behavior since last year. While this may be useful in most simple use cases, in some more complicated League Meet setups this may not make sense. Consider a few scenarios:
1. Two Leagues come together for inter-league play. The combined rankings now list all teams from both leagues, even if only a small subset of those teams are present. The rankings are now intermixed, and have very little meaning in terms of future rankings if those Leagues will be at different League Tournaments.
2. Following from above, now when the Leagues split and have their separate meets, the combined ranking will forever contain the last known snapshot of the other League.
3. One large League has multiple League Meets at the same time. The rankings at each individual event only update based on the matches played at that event, so the rankings shown at each League Meet are all incorrect, except for within the relative ranking of the teams at that League Meet.
4. Prior to RP and TBP being averaged this year, if League A and League B played each other in inter-league play and League B had already had 2 meets while this was the first meet for League A, then all teams in League B would almost surely be ranked higher than those in League A in the combined rankings during the Meet by virtue of having played more matches.

Because the situation isn't always straightforward, we stuck with the "this event only" ranking on the preview and results display. It's a known quantity, easy to explain, still shows you your relative performance at that event, and does not suffer from any of these edge cases that provide sub-optimal results for the combined rankings.

Fundamentally, at issue here is that the combined rankings at any given League Meet don't mean anything specific since they aren't used at that Meet for anything. At a League Tournament, filtered combined rankings is guaranteed to be right because this is the final stage and thus 1) we can filter out teams that are not present and 2) we know the match data is up to date.

Because of this, I think this will take more thought than simply swapping League Meets to display the same ranking calculation as what League Tournaments do on the Match Preview and Match Results screens. For example, we could filter out teams that are not present like League Tournaments do. This fixes the issue of teams continuing to show up from prior inter-league play, but now makes it difficult to tell where you are within your League if the some teams from your League are not at the event. If the team that was rank 1 does not come to a Meet, then everyone moves up one spot in the combined ranking, but the team that is now shown to be number 1 might not be number 1 at the next meet if the other team shows up.

**Comment by jvens** [comment]
@adwiii, these are some very good points, many of which I hadn't considered.  Currently we have an inconsistency in what rankings are displayed on the audience display.  The team ranks on the match preview/results displays are "this event only."  The Ranking that is shown on the Audience Display when you click `Show Ranking & Results` in the video switch are the "combined" rankings.

We have structured our leagues this year such that they are much larger and only about half the teams in the league will come to each league meet.  This gives the teams more flexibility to pick which meets fit best with their schedule.  With RP and TBP averaged instead of totaled once all the teams have played in a least one meet then the rankings are more-or-less meaningful.  Sure, only the teams at the event are going to be able to shift in rankings, but they can get some idea of where they sit overall.  We also have the cases where a league has 2 meets at the same time with different teams in it, and in that case the rankings aren't as meaningful, but still have some meaning.

I am not sure how to handle a inter-league meet.  That isn't something we have ever done in Iowa, so I don't know much about how they are suppose to work or what is expected.

I was asked at an event this weekend by a team why they were ranked one value on the match preview but they had a different rank on the Rankings & Match Results page I put up on the audience display, so the current system is causing confusion.  At the time it took me doing some investigation to figure out exactly what was going on.

One question is since rankings aren't actually used for anything during a meet anyway, and there are so many edge cases on how they are calculated should we be showing them at all on the match preview/results pages?  I like the combined ranking because it shows more or less what the rankings would be going into the league tournament, but the "This event only" rankings are confusing and don't really serve a purpose in my opinion.

Also, your points above have convinced me that if you want to say "as designed, won't fix" I would be ok with that decision for the original question.

**Comment by maths22** [comment]
This is resolved in v3 (for Freight Frenzy).
