### ISSUE TITLE
Print button not working for Announcer Reports

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#446]
Exactly title.  The print button on the announcer report page does not work on v1.1.2.  I have tested on two separate computers.

**Comment by pstrones** [comment]
I did not experience this issue today on v..1.1.2 for a qualifier that we ran in AZ.  Printing the announcer report worked perfectly.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jvens** [comment]
I just tried again on my desktop computer now that I am home and also can't reproduce it.  I saw this on both the computer running the score system today as well as another laptop that was connected to the score system network.  That second laptop worked just fine to print the match list, but the button for the announcer report wouldn't do anything.  I then tested on the computer running the score system and had the same issue with the button not doing anything.  I will be able to pull the logs from the system tomorrow and can post them if that helps shed some light on this issue.

**Comment by adwiii** [comment]
@jvens what browser were both of those laptops running?

**Comment by jvens** [comment]
Both browsers were running Chrome on Windows 10.  I didn't have a chance yesterday to pull the logs, but I will be able to when I get off work this evening.

**Comment by adwiii** [comment]
I am happy to review the logs, but I doubt there will be anything about the printing if everything else about the page worked fine. I will look into it more and see if I can find anything.

**Comment by pstrones** [comment]
I am attaching what it looked like from the AZ event where the print function worked for the announcer pages, maybe it would be good to view what the screen looks like to compare the possible issue that has been reported.  The screens I have are the initial screen for the report, then the screen when the print button is hovered over with the mouse and the next when the print button is selected.  The last one is also the one where print options are available, the printer, number of copies, etc.  Was the event it league based or qualifier based?

This is all from the same scoring version that the problem is being reported.  We also utilize chrome on our laptop and didn't experience the same issue.


Patricia (Patti) Strones
FIRST ®  AmeriCorps VISTA, Southwest Region



[72dpi_sm2]


For Inspiration and Recognition of Science and Technology

200 Bedford Street  |  Manchester, NH 03101  |  www.firstinspires.org<http://www.firstinspires.org/>

Phone:  928-607-7563  |  pstrones@firstinspires.org<mailto:bmartin@firstinspires.org>



[cid:77d3fd82-6704-45b4-9a78-56079b3a7dd0]


________________________________

**Comment by jvens** [comment]
I have attached the log.  Also I tried starting the server and printing the announcer reports again from chrome and now it works.  So I guess that restarting the score system must have resolved the problem.  If you can't find anything obvious on your side I am happy if you call this a fluke and close the issue.  If I see it again I will make sure to save the logs from the Chrome Developer Console and reopen the issue.

[2019_11_08_06_01_07_PM_err.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/3833820/2019_11_08_06_01_07_PM_err.log)

**Comment by jvens** [comment]
I received a report of this same exact issue happening at another event, but this time it was for printing the match list.  She said that the print button did not work at all, and she ended up using CTRL+P to be able to print out the match list.  Again, we can't replicate the issue on the same computer after having shut everything down and restarted it.  I gave her instructions for how to save the client-side logs from the Chrome DevTools if it happens again, but without that info all I can do is say we have seen it again.

**Comment by adwiii** [comment]
I have tried to do some research into this, and I do not know what could be causing this. I still have not been able to replicate the issue locally. The button on the page has a `onclick="window.print()"`, which my understanding is should behave the same as CTRL+P. I will keep an eye out for this moving forward, but in the mean time it seems CTRL+P might be the way to go if this keeps happening.

**Comment by jvens** [comment]
Close as cannot replicate.  I haven't seen this issue again.
