### ISSUE TITLE
Award entry doesn't match judges award template

### ISSUE THREAD

**Issue by wcraigtrader** [FIRST-Tech-Challenge/scorekeeper#461]
In the Chesapeake region (Virginia, Maryland, DC) there's a script template (spreadsheet) that the judges use to write up their awards which uses this format:

* Second runner-up team number, team name
* First runner-up team number, team name
* Judges comments
* Winning team number, team name

However, when editing the awards in the award manager, it expects you to enter the award data like this:

![FTC-Awards-editing](https://user-images.githubusercontent.com/972263/69543104-de57f100-0f5a-11ea-9344-2f438051c458.png)

When you're in a hurry, the on-screen editing order can be error-prone, due to the mis-matched names and the discontinuity in order. (This appears to be because of the CSS and flow.) While I understand the desire to save screen real estate, I think that errors would be reduced if the CSS forced everything to single lines:

![FTC-awards-editing-2](https://user-images.githubusercontent.com/972263/69543416-91c0e580-0f5b-11ea-93d8-0d37715fbcda.png)

Changing the field descriptions would also help:

![FTC-awards-editing-3](https://user-images.githubusercontent.com/972263/69543613-f9773080-0f5b-11ea-892b-a1f60c5c519d.png)

And, of course, changing the editing ordering to match the judging template would be ideal, but I don't know if that template is consistent across the rest of the FIRST regions:

![FTC-award-editing-4](https://user-images.githubusercontent.com/972263/69543746-46f39d80-0f5c-11ea-89d3-65e18382a74d.png)

**Comment by adwiii** [comment]
We can definitely change the wording so that it more closely matches the award script, though likely keep the original, like "First Runner-up (Second Place)" and make them one column. 

I do not think swapping the order at this point makes sense more broadly for two reasons. Primarily, I worry that it may confuse people who are used to having the awards in this order since it has been in this order and basic UI for a season. My concern would be that they accidentally enter awards with third and first swapped because the UI is the opposite of their last usage of the software. Secondarily, in this case it would affect fewer people if the local spreadsheet was changed to match the entry UI instead of the other way around. Since the workflow between the judges deciding the awards and then the awards getting entered into the scoring system can vary, I think it would be best for the scoring system to remain constant so regions can design their workflow around a known quantity.

**Comment by adwiii** [comment]
With `v1.3.0` the UI has been updated on the award entry to be more consistent with other wording, and they appear as one column:
![image](https://user-images.githubusercontent.com/9453262/72026166-92ca7f80-3248-11ea-94ea-22b60c320f9f.png)
