### ISSUE TITLE
audience display keeping scores from previous match 

### ISSUE THREAD

**Issue by GamingWithaAlexYouTube** [FIRST-Tech-Challenge/scorekeeper#464]
when ever you start a match right after one some times only the audience display still shows scores form the previous match until the referee would put a score in for that match then it resets.

**Comment by pmichaud** [comment]
We observed this behavior at our December 14th event as well.  After doing "Randomize Field" and "Show Random", when the scorekeeper hits "Show Match" the scores from the previous match are displayed instead of zeroes for the upcoming match.

The scores properly clear when the match begins and referees begin entering scores for the newly played match, but it's very confusing to the audience, teams, and referees when it happens.

I will see if I can come up with steps to reproduce this behavior in our next event (Saturday Jan 4).

Pm

**Comment by ofekashery** [comment]
We experienced the same issue today with version 1.2.1.

**Comment by ofekashery** [comment]
Here is the video: https://drive.google.com/file/d/1CBEvh_w6oPayGl1OhZ-pmMo_xOa7m5aa/view

**Comment by ofekashery** [comment]
We experienced it again, after match posting. Watch the full match on [YouTube](https://www.youtube.com/watch?v=1T17JyEz9ng).
![Kapture 2020-01-31 at 17 28 30](https://user-images.githubusercontent.com/16443111/73551483-23167180-444f-11ea-8c07-5e60d432d168.gif)

**Comment by maths22** [comment]
This is resolved in v3 (for Freight Frenzy).
