### ISSUE TITLE
Score Tracker allows three Skystones to be entered.

### ISSUE THREAD

**Issue by gearsincorg** [FIRST-Tech-Challenge/scorekeeper#466]
In autonomous it's possible for refs to enter on their tablets three or more skystones have been transported.   I don't know if this is being permitted because of possible returns, but if there are no returns, then this isn't a possible result.

If the referee records that there have been three Skystones transported in Auto with no returns, the team gets credit for two SkyStones and one Stone (good), but the code assumes that the two Skystones were delivered first, thus giving them the maximum possible points.  But this may not have been the case.  The first or second stone may have been the regular stone.  Since this condition is clearly impossible it should be flagged. 

It seems that this situation (more than two SkyStones delivered with insufficient returns) should be highlighted red on the tablet on the final preview screen.

**Comment by tvbarnette999** [comment]
The scoring system does not assume the two Skystones were delivered first. It calculates the Skystone Bonus based on the 1st and 2nd stones's input values. The stones should be marked in the order they are delivered. The 3rd-6th stones cannot gain the Skystone Bonus, even if they are marked "Skystone". If a Skystone is delivered, returned, and delivered again, then it should be marked as a Skystone for both deliveries, and the "1st Stone Returned" field should be set to "Skystone". This allows the scoring system to properly deduct the Skystone return.
For ease of use and continuity across seasons, we try to make the referee inputs operate by "enter what you see" to minimize uncertainty about how to use the software when unusual things happen. Thus, it allows you to mark 3-6 as Skystone, but still scores it properly. 

You are correct, entering Skystone, Skystone, Skystone, Return = 0 is generally an impossible/incorrect input. We did not implement the logic to mark that because it doesn't affect the scoring, and adds complexity and risk of error on our part, and gets more complicated if more than 1 return occurs. If it is causing problems that it doesn't flag extra skystones, we can look into that some more.

**Comment by gearsincorg** [comment]
Thanks for the detailed explanation.

I agree that letting the Ref enter what they see is key to making their job easier and more accurate.  I also agree that checking for the various invalid combinations would be tricky, but doable.

My only concern is that if you permit a clearly incorrect data-set be entered then you really can't say that the scoring is correct/unaffected.

Given that Skystone, Skystone, Skystone, Return = 0 is not possible, then there must be an error in what was entered.  Once you accept that, all bets are off.  Either 1) too many boxes were clicked (maybe there were only two stones delivered), or 2) one or more of the SkyStones are incorrectly recorded (and we don't know which ones).  or 3) there should have been at least one 'return' listed.  Only the score tracker knows,

Each of these scenarios could result in a different score (ranging from 6 to 22 points), so I don't think it's fair to say it does not effect the scoring.   

The upside is, that this is one instance where you know for sure there has been a human error, and you have the perfect opportunity to correct it before it becomes official.

**Comment by jvens** [comment]
I would like to point out that there are actually 4 skystones on the field and there is a scenario where a team could deliver both their skystones and one of their opponents.  And yes, I am well aware that this scenario would also lead to penalties for interfering with the opposing alliances quarry during autonomous.  My point is there are always more edge cases, and it is really hard to predict every possible scenario.  

My personal opinion on this is that it is the referees responsibility to be diligent and ensure the correctness of scores.  We also confer after each match between the penalty refs and the score tracking refs to ensure that everything was correctly accounted for.  If the refs are reviewing the scores after the match before submitting this is something that they would likely quickly catch.  There is also something to be said for not creating a false sense of security that the score system will catch all mistakes so we don't have to be that diligent when entering and verifying scores.

I do agree that this is an edge case that is relatively easy to catch similar to a skyscraper being taller than the number of stones placed, but you have to draw the line somewhere.  What we certainly don't want is refs trying to enter a valid score but the score system thinking that it is invalid for some reason and not allowing it.  Just my 2 cents, I am not a dev on this project.

**Comment by gearsincorg** [comment]
Point Taken.
