### ISSUE TITLE
Mac: I downloaded newest version, keep showing 1.1.0

### ISSUE THREAD

**Issue by deenial** [FIRST-Tech-Challenge/scorekeeper#494]
Hello!

Mac user. I was running version 1.1.0 (I used it many times), then downloaded 1.4.0 and executed it as the manual says.
However, the top of my browser keeps saying "**FIRST Tech Challenge Live v1.1.0 running at 127.0.0.1**"

What is going on?
This also happened when I tried to use 1.2.1
Is there a step I am missing when using a newer version after using an older one on mac?

p.s. Yes, I terminated the 1.1.0 application before trying the new one
I did not delete the 1.1.0 folder, I'm afraid of losing my saved tournaments.

**Comment by adwiii** [comment]
This sounds like it could be similar to #55 and #146. From my understanding, on mac closing the terminal does not stop the scoring system (#55). When you run any copy of the scoring system it will first scan to see if there is another copy of the scoring system already running and if so it will open the one that was already running instead of the new one (#146). 

You can use the Activity Monitor and kill java and that should close any copy of the scoring system that is running or restart your machine and then run `v1.4.0`. If this does not solve the issue, then please post the log files here from your `v1.4.0` runs and I will take a look.

**Comment by deenial** [comment]
Killing Java worked.
Thank you very much!
