### ISSUE TITLE
Dual Division Team Entry

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#497]
For a dual division event, if you add the teams to the event by adding them to the child events directly without first adding them to the parent event, they wind up not showing up on the editable team list on the parent event, but they do show up on the competing teams report.  Additionally, they don't actually get saved in the database as award winners, so when I restarted the system after the event the awards were missing all their winners.  I was able to fix the issue with some database surgery, but this does also mean the db submitted to FIRST won't have award winners.

**Comment by pstrones** [comment]
My understanding is that you would enter the team names in the main (parent) event for dual divisions since the system has the capability of assigning the teams randomly to the divisions available.  Then you have the ability to review the assignments and determine if there are any issues/concerns in each division along with identifying those teams that are already advanced to Houston (if a State final event).  Then the awards would all be in alignment with what is entered as they aren't entered in the separate divisions (child event).   It doesn't seem like a benefit to enter the teams as described above.  If you marked teams as advanced in the division (child) event, it would not reflect in the main (parent) event like it should.

**Comment by adwiii** [comment]
We intended for both use cases to be possible. If the event has pre-assigned the divisions, then you can add them directly to that division and it *should* put it both in the division and the main event. If you do not have a pre-assigned set of divisions, the scoring system can generate them for you as you say by adding them to the main event and then randomly assigning them.

It turns out that in this case there is a bug where adding to the division event will cause issues later on whereas adding to the main event and then assigning division (either randomly or manually), then it will cause the issues @maths22 discusses.

**Comment by maths22** [comment]
That's exactly my situation.  In Illinois we generate the division lists with a process outside the scoring system, and then import the lists.

Separate note: is there somewhere I should send the fixed db that actually has award winners in it?

**Comment by adwiii** [comment]
This has been addressed in `v1.4.2` - adding teams to the division event will now properly propagate back up to the Inter-Division Finals event. Any events that were created before `v1.4.2`  in this manner can be imported into `v1.4.2` and the databases will be repaired. However, if awards had already been entered in the prior version, they will have to be re-added in `v1.4.2`.
