### ISSUE TITLE
Question About Archived Data

### ISSUE THREAD

**Issue by MentorMike** [FIRST-Tech-Challenge/scorekeeper#503]
Hello,

We're trying to post videos from the Louisiana Regional Championship that were recorded without the scoring overlay, and would like to to screen-cap the Match Preview screens from the intros.

Is there a way to pull up the match preview screen for matches that have already been played?

Thanks and good luck to everyone still competing/hosting events!

**Comment by adwiii** [comment]
The rankings shown on the Match Preview is a complicating factor. There is no good way to have the system show the Match Preview as it would have been at that time without "re-playing" the event by entering everything in by hand into a new event. 

If you have the database from the event, you can make the system show the Match Preview for every Match again but with the final rankings. First, make a backup of the database because this process will put it in an undesired state. Then, you can have it show each Match Preview by loading the Match for play, then showing the Match Preview. Each Match Preview screen will show the final ranking of the Teams based on all Matches played, even those after the Match being previewed. If you do this route, I suggest posting a note with the videos that the rankings shown are not necessarily correct.

**Comment by adwiii** [comment]
Whoops, forgot about eliminations matches and archived state. If the event has been uploaded to *FIRST* then it will not let you do that, and if eliminations have been played (which since this is a championship I assume they have been) then you cannot get to qualifications anyway.

If you can post the database here then I can post back a version that will let you access qualifications, a version for semi-finals, and a version for finals. Cumbersome, but doable.

**Comment by MentorMike** [comment]
@adwiii We do have the database, and have the event open, we just can't figure out the physical steps to get the match preview to show. We've tried the standard load next match/show preview, and it doesn't seem to do anything?

**Comment by MentorMike** [comment]
@adwiii Thanks, trying to figure out how to zip the DB file as the system won't let me attached a DB

**Comment by MentorMike** [comment]
@adwiii  Okay, I think this worked...
[2020_Louisiana_FTC_Regional_Championship.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/4277411/2020_Louisiana_FTC_Regional_Championship.zip)

**Comment by adwiii** [comment]
I have attached a zip folder containing the match preview screens from all of elims and a database that has been rolled back to qualifications.

I thought some more about it, and you can actually get the rankings to be correct though it requires a few more steps. You need to start with the last Match (number 24), and then work your way back to the beginning. For each match do the following:
1. Press "Replay" on the Schedule tab of the Match Control Page
2. Press the "Match Preview" button at the top
3. Take a screenshot of the Display showing the Match Preview
4. Press "Randomize" at the top of the Match Control Page. 
5. Go to the preceding Match in the list and press "Edit" on the Schedule tab
6. Change the score and then put it back (for example, add a Stone placed in Autonomous and then remove it). This will make the score be the same but will now enable the "Commit" button. 
7. Press "Commit" on the Score Edit tab. This will cause the rankings to update.
8. Repeat from step 1.

By randomizing the Match, but not playing it, the Match will be excluded from rankings. 

Once you get to Match 1, there will not be a previous Match to edit to update the rankings. As such, I have included Match 1 in the zip file as well. 


Let me know if you run into any issues.

Zip with images and db:
[2020_LA_match_previews.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/4277620/2020_LA_match_previews.zip)

**Comment by MentorMike** [comment]
@adwiii Thanks Trey, this is perfect!!!
