### ISSUE TITLE
Scorekeeper SRC

### ISSUE THREAD

**Issue by AlexejheroYTB** [FIRST-Tech-Challenge/scorekeeper#507]
Will the SRC of the Scorekeeper ever be publicly released?

**Comment by adwiii** [comment]
We have no plans to release the source at this time. The nature of this software presents two main challenges. To begin, *FIRST* provides event day support for those using the software and we provide support here on the GitHub to help volunteers with issues they face before and after events. If the source code were publicly available, this could lead to many modded versions of the scoring software becoming available for people to use, and *FIRST* would not be able to provide support for these different versions that they do not control. As a follow-on to this, there are some key functions of the scoring system that must be the same and uniform and not modified across events, ie rankings need to be calculated the same, the point values for the scoring achievements need to be the same, etc. Secondly, as we transition from one season to another, the scoring system becomes confidential information while we work on adding the new game specific items to be ready for the new season. 

These two factors would make it difficult for the development team and those that support the software to do their jobs to support the community. Due to this, we do not have plans to release the source.
