### ISSUE TITLE
Matchmaker Preview Shows Blank Matches

### ISSUE THREAD

**Issue by bsimmons99** [FIRST-Tech-Challenge/scorekeeper#52]
Once matchmaker has been run, clicking "Preview" will have the table of matches show no team names. Does not appear to affect match schedule. Matches are present if page is refreshed but disappear again upon clicking preview.

[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2458550/db.zip)

**Comment by adwiii** [comment]
Preview is meant to be a check of "what would the match times look like if I generated using these times" and thus inherently does not contain teams. The answer here is likely that the preview button should be disabled once matches have been generated since you no longer have anything to preview - just the final match list you already generated.

This would then be related to #45 because currently there is no way to change the match schedule once it has been generated. (It will ask you if you are sure, but does not actually go through with creating the new match schedule).
