### ISSUE TITLE
Generated Accounts Lost Permissions Mid-Event

### ISSUE THREAD

**Issue by silvanoc109** [FIRST-Tech-Challenge/scorekeeper#525]
### **Initial Info**
The day before the event, after importing the information from FTC Scoring to FTC Live, the "Generate Random Accounts" action was taken to create referee and inspector accounts.

During the initial set up of the event, the router/network running the event was reset a few times, changing the IP address.

### **The Issue**
Mid-event, both the referees and inspectors signaled that they could not see the options in the FTC Live software that were previously available to those account holders.

Signing out and then back in didn't work. Clearing the browser cache did not work.

This issue was ultimately resolved by manually creating new accounts. Those accounts only worked if the option selected was to assign them to **ALL** active events on the server. (Even if there was only one event on the server)

### **To Reproduce**
1) FTC Live was running
2) Tablets were connected and logged in with generated accounts
3) Router was reset (a few times)
4) Tablets were still logged into inspector accounts, but the inspection option disappeared
5) Restarting the server did not work
6) Logging in/out on tablets did not work
7) Creating a new account with permission to inspect allowed inspection to take place

### **Devices**
Windows 10 - FTC Live v3.1.1
Amazon Fire Tablets - Connected to Private Wi-Fi to Access FTC Live

### **Additional Context**
Date of Event: Oct 30, 2021
Submission ID: 04238ef0-29e9-4fd1-989c-02e3c6739a0f

Here is the last log available from the system.
[2021_10_30_09_13_41_AM.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/7447697/2021_10_30_09_13_41_AM.log)

**Comment by adwiii** [comment]
We have confirmed this bug and have developed a fix that will be part of our next release. Until then the only solution is the one you described, using manually created accounts. For others facing this issue:

* Open the "Event Admin" menu
* Select "Create User"
* For roles, select the role(s) you want for "All Events" (the bug is with roles for specific events, so you must pick "All Events" and not your event)

For more context, the bug is semi-random and is related to the scoring system being restarted. The issue will not resolve on its own unless the server is restarted, and even then restarting the server does not always fix the issue.

**Comment by tvbarnette999** [comment]
This has been fixed in v3.4.1.
