### ISSUE TITLE
Red vs Blue Scoring

### ISSUE THREAD

**Issue by mbcamburba** [FIRST-Tech-Challenge/scorekeeper#534]
**Is your feature request related to a problem? Please describe.**
While the field is set up with blue on the left and red on the right (when looking from the Carousel), the scorekeeper screen is split with red on the left and blue on the right.

**Describe the solution you'd like**
It would be helpful to have the scorekeeper screen set up like the field with the blue on the left and the red on the right.

I will take a screenshot of this at our next meet.

**Comment by adwiii** [comment]
As you describe, from the [Audience's perspective](https://firstinspiresst01.blob.core.windows.net/first-forward-ftc/game-manual-part-2-traditional.pdf#page=7) (which looks from the Carousels), the field is set up with blue on the left and red on the right. Accordingly, the scoring displays default to have blue on the left and red on the right. However, the system assumes that the scorekeeper will be on the opposite side of the field, and so by default the Match Control Page has red on the left and blue on the right to match that perspective. 

If for whatever reason the display or scorekeeper have a different perspective, both the Match Control Page and displays offer settings to swap the colors to match the desired perspective. I have detailed below how to change these settings.

## Match Control Page
On the Settings tab, there is a checkbox for "Flip Alliances (Red on Right)". 
![image](https://user-images.githubusercontent.com/9453262/141849141-6f7a3901-2ded-4daa-8c05-b96a2aed99bc.png)
Enabling this checkbox will swap the alliances on all tabs so that they appear like this:
![image](https://user-images.githubusercontent.com/9453262/141849290-a12ba61a-7435-4767-ae3a-b109c225e6aa.png)


## Displays
On the displays, the setting is under the "Advanced Settings" section where there is a dropdown for "Alliance Orientation":
![image](https://user-images.githubusercontent.com/9453262/141849528-e0f54cf4-e7fd-4c76-ae27-e2999f28026f.png)

Once swapped, the displays will appear as expected:
![image](https://user-images.githubusercontent.com/9453262/141849721-5e62ffbd-1a0a-4ab3-9fa8-833011a71100.png)
