### ISSUE TITLE
Inspection Data Entry needs Pass button to work without checking all the inspection items

### ISSUE THREAD

**Issue by Crossle86** [FIRST-Tech-Challenge/scorekeeper#536]
At our event we had 3-4 inspectors operating and only one tablet. And since the kids are supposed to bring a self-inspection sheet with them, our inspectors use the paper sheets. That means one person takes the passed sheets and enters them into the scoring system. We had to check all the boxes before we could pass the team even though that had already been done by the inspectors. The previous iteration of the scoring system allowed this. It would be nice to have the requirement that all boxes be checked before pass was a configurable option.

**Comment by adwiii** [comment]
I understand your request is slightly different, but the system does allow for a manual bypass to mark a team as "Passed" without checking all of the form items. If you are logged in as an Event Admin user, on the inspection page you will see the following link in the upper right:

![image](https://user-images.githubusercontent.com/9453262/142035093-9988bd28-9e58-4999-a68b-ae15e22fdd36.png)


This link *should* show up for Lead Inspectors, but currently doesn't due to a bug. However, if you directly type the link in the browser, e.g. http://localhost/event/test/inspect/robot/override/ it will work as expected for the Lead Inspector (shown below). This will be fixed in the next release to show the link for the Lead Inspector as well.
![image](https://user-images.githubusercontent.com/9453262/142033388-bfb265ed-ff5b-4bb6-8d64-61cc845e5b4c.png)

Note that this does not check all of the inputs as you requested, but it does update the status that is displayed everywhere. Adding a way to check all of the inputs is not something we are currently considering. 

I will leave this issue open until the above fix has been released.

**Comment by Crossle86** [comment]
Thanks, that will solve my problem.

**Comment by maths22** [comment]
v3.2.0 restores the link to the lead inspector override
