### ISSUE TITLE
Unable to start next match, previous match committed but still shows up as active

### ISSUE THREAD

**Issue by khojlo** [FIRST-Tech-Challenge/scorekeeper#537]
We were using FTC Live v3.1.4 and run into an issue where even though previous match was committed and posted and next match was loaded and randomized but wouldn't allow us to start. Refer the attached screenshot that shows not having "start match" option for match 7 while match 6 had already been committed and posted but still the top bar continued to show 0.01 seconds left for match 6.

This was the sequence of events:
- Match 6 was being played
- At the end as referees were finalizing the scores, we loaded the next match (7)
- For match 7, we did "show match" which got displayed on both field and audience display
- Once referees submitted their scores, we committed and posted the scores and those were displayed
- At this point, referees had match 7 shown on their tablets
- We then randomized the match 7 and show random, this too got displayed correctly
- We then did show match but could not play match as that option wasn't there, instead "Abort Match" option was there.
- Match 6 was still shown in the top bar as the active match with 0.01 seconds left
- Not sure what would have "Abort Match" at this point would have done (meaning abort 7 or already committed 6), so we did not press that button.
- We even tried to randomize/show random/show match again for match 7 but that still did not release match 6 from being active match

At this point, the workaround we found was to Exit the Match Control screen and come back into Match Control. This cleared up match 6 and we could then start/play match 7.
![IMG_9991](https://user-images.githubusercontent.com/94494646/142082541-cd32c392-03f9-43cf-8d56-c3b087fa2430.jpg)

**Comment by adwiii** [comment]
We discussed this a bit offline, but I am posting here as a followup to others. This appears to be a bug in the Match Control Page, but we do not have a clear explanation as to the cause. We have tried to duplicate this behavior to understand the problem and develop a fix, but have been unable to do so. We will continue to monitor the issue to try to determine a root cause. In the mean time, if you encounter this issue again please:
1. Before proceeding, open the Chrome Developer Tools (F12) and navigate to the "Console" Tab at the top. Please copy the most recent set of lines at the bottom, being sure to include any red text, and reply to this issue with that data. This will greatly aid in narrowing down the issue.
2. To recover from the issue, refresh the Match Control Page *after* committing/posting the Match. This will ensure that the data has been properly saved. If there is an issue committing the match (which we do not expect, but to be safe), the Match Control Page will show a red pop-up warning with further instructions.

If you have any difficulties with this at an event, please also feel free to reach out to us through the Live Support Chat available from the "Help" tab on the Match Control Page or the "Help/Feedback" page linked on most other pages.

**Comment by maths22** [comment]
We have improved the internal of the match control page and believe this issue has been resolved; please open a new issue if this happens again
