### ISSUE TITLE
Able to deliver more ducks than on the field

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#545]
**Describe the bug**
It is possible to score more than 10 ducks delivered on the score tracker tablet.

**To Reproduce**
1. Score 11+ ducks delivered

**Comment by adwiii** [comment]
Placing limits on scoring achievements has been discussed in the past (see #14, #200, and particularly the discussion in #13), with the conclusion that the scoring system will only enforce a handful of impossible scoring states, particularly relating to *conflicting* information. Otherwise, the scoring system will not enforce numerical limits based on the number of Game Elements scored except for the Team Specific Elements due to the listed concerns.

For FREIGHT FRENZY, the only limits enforced at this time are that the maximum number for the "Capped" achievement is 2 and that the Match Control Page enforces that the Shared Shipping Hub is not listed as being Unbalanced in favor of both Alliances.
