### ISSUE TITLE
Overlay version of "Show Preview" display

### ISSUE THREAD

**Issue by pmichaud** [FIRST-Tech-Challenge/scorekeeper#555]
Problem:  When using the audience display screen to help drive a livestream output, the livestream sits on the "match preview" screen for long periods of time (while robots are being set up), which is kind of a boring display to have up for a long time.  

Desired Solution:  We'd like an overlay version of the Match Preview screen (displayed when "Show Preview" is pressed), which previews the teams using the lower third but allows chroma-key camera image to come through as well so audience can watch the field setup.

This could be done with a "preview overlay" option in the Audience Display settings, similar to what is done for awards and alliance selection overlays.  It would be potentially better to have a separate "Show Preview (Overlay)" button on the Match Control page, so that the operator could choose to do a full-screen match preview (no overlay) and then easily swap to the overlay version afterward but before randomization takes place.

Alternatives considered: Alternative 1: Currently we work around this by having our livestream producer manually switch to a full camera scene (no overlay) whenever the match preview page has been up for a sufficient amount of time.  The producer then has to remember to switch back to the overlay scene whenever randomization/match start begins, otherwise the view doesn't have the overlay graphic when the match is being played.

Alternative 2:  The scorekeeper sits on the "Video Switch" tab of Match Control and uses the "Show Video Only (Overlay)" button to reveal the camera image.  But the lower-third of the display is then blank, or shows part of the camera image that would normally be obscured by an overlay graphic.

**Comment by jvens** [comment]
@pmichaud, I have another workaround/solution to this problem that I have been using at my events with OBS Studio.  When you add the browser source in OBS Studio there is an option to add custom css which is used to change the way the page renders on the livestream.  Linked below is the css that I use which make the background transparent during match preview, show random, and show scores.  Since this exists entirely inside of OBS this does not affect any of the other displays other than the livestream.  

The other big advantage of this is rather than using a chroma key it sets the alpha channel of the overlay, so you can get the partial opacity and you don't have to do any keying out.  It currently doesn't behave all that well with the hybrid alliance selection page so for that I use a second browser source without the custom css and key it out like normal.  If you have any questions about how to use this don't hesitate to ask and I can create more comprehensive step-by-step instructions for how I do it.

If the score system development team would like to copy and use any of my css code into the official release you are welcome to do so.  Consider it under MIT License. 

https://gist.github.com/jvens/3f9448189d046c37fa3ac41f12e343d2

Examples:
![image](https://user-images.githubusercontent.com/7074504/151481470-77513437-585a-4bb2-a69f-225f7fff03e8.png)
![image](https://user-images.githubusercontent.com/7074504/151481527-9e445f07-372b-4f89-b210-7ad93c669663.png)
![image](https://user-images.githubusercontent.com/7074504/151481589-48ca2b57-1d19-4eef-b837-dd65f4c93713.png)

**Comment by pmichaud** [comment]
@jvens This is a genius workaround, thanks for offering it!  I may indeed give it a try, and it's certainly more usable than what exists in the scorekeeping displays now.  I'm likely to play around with the CSS a bit as well to see what other options I can come up with.  I definitely like having the image in the background in the randomization and final score screens.

I think I'd still like a lower-third overlay option for the match preview page, however.  We tend to shoot our camera angles from above the field instead of an audience view, and the camera image when scaled for the overlay screen often doesn't extend to the bottom of the OBS canvas.  As a result there will probably be a big black section at the bottom of the display.

Still, a great idea and I look forward to playing with it.  

Pm

**Comment by pmichaud** [comment]
Oh, in OBS I can add a "Color Source" source that places a background on the lower-third, to obscure the blank space below the camera image.   That might work out okay.

Pm

**Comment by khojlo** [comment]
> @pmichaud, I have another workaround/solution to this problem that I have been using at my events with OBS Studio. When you add the browser source in OBS Studio there is an option to add custom css which is used to change the way the page renders on the livestream. Linked below is the css that I use which make the background transparent during match preview, show random, and show scores. Since this exists entirely inside of OBS this does not affect any of the other displays other than the livestream.
> 
> The other big advantage of this is rather than using a chroma key it sets the alpha channel of the overlay, so you can get the partial opacity and you don't have to do any keying out. It currently doesn't behave all that well with the hybrid alliance selection page so for that I use a second browser source without the custom css and key it out like normal. If you have any questions about how to use this don't hesitate to ask and I can create more comprehensive step-by-step instructions for how I do it.
> 
> If the score system development team would like to copy and use any of my css code into the official release you are welcome to do so. Consider it under MIT License.
> 
> https://gist.github.com/jvens/3f9448189d046c37fa3ac41f12e343d2
> 
> Examples: ![image](https://user-images.githubusercontent.com/7074504/151481470-77513437-585a-4bb2-a69f-225f7fff03e8.png) ![image](https://user-images.githubusercontent.com/7074504/151481527-9e445f07-372b-4f89-b210-7ad93c669663.png) ![image](https://user-images.githubusercontent.com/7074504/151481589-48ca2b57-1d19-4eef-b837-dd65f4c93713.png)

Hello Jeramie, I would like to discuss this little more with you and sent you a LinkedIn invite (coming from Shail Goel). I really liked your this idea and want to discuss different scenes you create in OBS to account for this as well as other aspects of streaming matches. Could you please accept my invite so I can DM you? Thanks

**Comment by maths22** [comment]
An overlay preview is now an option as of the Freight Frenzy offseason release.
