### ISSUE TITLE
Matchmaker not working on raspberry pi

### ISSUE THREAD

**Issue by Infinity8806** [FIRST-Tech-Challenge/scorekeeper#575]
**Describe the bug**
Matchmaker not running on raspberry pi

**To Reproduce**
1. Start Software
2. Creat an event
3. Try to run match maker to create an event schedule
4. No error ever show up, but a schedule is not generated

**Expected behavior**
Matchmaker runs and a schedule is generated

**Device (please complete the following information):**
 - OS: Latest version of Raspbian
 - Chrome
 - Raspberry Pi 4 8gb

**Comment by tweirtx** [comment]
Able to reproduce on my 3B+ using a 64-bit OS image, however it works fine on a 32 bit OS image. My guess is that MatchMaker is not compiled for 64-bit ARM Linux (or at least, whatever logic chooses the executable for MatchMaker doesn't understand 64-bit ARM, my guess is on a Pi at least it would work fine if it knew to run the 32 bit ARM executable)

**Comment by jvens** [comment]
I don't have a Raspberry Pi available to test on with me, but I suspect the issue is you don't have Multiarch installed on the Pi.  Looking at the dependencies of the MatchMaker with `readelf` there are no external dependencies beyond `libstdc++.so.6`, `libm.so.6`, `libgcc_s.so.1`, and `libc.so.6`.  All of these would be provided in 32bit versions by multiarch, however I have never tried to install or use multiarch on ARM so I don't know if Raspbian even supports it.  You might try starting with https://wiki.debian.org/Multiarch/HOWTO and see if any of that will work on ARM.  The only other option is for the developers to cross compile it for ARM64 and then pick the right version to run.  Running 32 bit applications on a 64 bit system requires 32 bit system libraries and if you don't have them it isn't going to work unfortunetely.

**Comment by tweirtx** [comment]
Through the magic of figuring out how CPU architecture detection works on Scorekeeper, I have determined that the architecture string of a 64 bit Pi from a Java context is `aarch64` which does not match the string of `arm` that the code is looking for.

**Comment by maths22** [comment]
Thank you all for the detailed investigation. As of v4.1.6, we are now shipping an aarch64 build of matchmaker for 64-bit ARM installations.
