### ISSUE TITLE
Root permisisons should not be required

### ISSUE THREAD

**Issue by maths22** [FIRST-Tech-Challenge/scorekeeper#58]
In many situations, particularly when using school computers, users may not have root permissions on their computers.  The startup script should not require root, it should just use a port 8080 or another higher-numbered privileged port.

**Comment by adwiii** [comment]
We have discussed this several times internally and came to the following conclusion, but welcome public input. Just to give you an idea of the thought process, the discussion went like this:

Using a port number that is not 80 requires everyone using the system to type in the port number since 80 is the default. Given the number of devices this could be, including many mobile devices for score tracking, we felt this was a large burden to place on a large number of volunteers. However, we acknowledge that not everyone can use port 80. So as a workaround, the script in the `bin` folder (not the one at the upper level), accepts command line arguments. Specifying `-p <port>` will cause the server to start on the specified port number, with the default being port 80 if none is specified.

This way, if users have the ability to use port 80, which simplifies everything, then it does. If the user knows that they cannot use port 80, then they can specify an alternative port.

A future feature might be that the server detects that it does not have access to open port 80 and asks the user to either 1) authenticate or 2) choose another port.

**Comment by maths22** [comment]
I'm mostly concerned that the new scoring system already has a bit more of a learning curve to getting started than the old one, and this is going to require a lot of scorekeepers using school managed systems to use the terminal, something that many likely do not do and that is honestly somewhat scary to a non-technical user.  Providing an option at least would be helpful.

**Comment by cmacfarl** [comment]
I agree with Jacob that we should be proactive with this.  Detect the
failure to open port 80 and perhaps automatically fall back to 8080.

The main landing page should then prominently note that it's on a
non-default port.

I think without this feature we will get a lot of support calls.

**Comment by adwiii** [comment]
Let's talk through what a reasonable course of action is here then. I have in psuedo code below an idea for how the server could choose it's port:
```
/*
 * Constraints: 
 * - Do not start server if there is an instance of the server already running
 * - Choose first port in a given sequence that the OS will let us bind to
 */
function startServer(portNumber):
  response = GET localhost:portNumber
  if (response is response from Scorekeeper):
    return
  try:
    bind(portNumber)
  catch:
    startServer(nextPortNumber(portNumber))
```

The idea is that for every port we try we check to see if there is a copy of scorekeeper already running, if so, we do not allow two copies of scorekeeper to run on the same system, so stop trying. Then, try to bind to that port. If you cannot bind, then try the next port in the sequence. I would imagine our standard sequence would be something like `80, 8080` and then we would need to come up with a way to generate infinite after that? Perhaps increment by 10? 100? 1000?


After the system has a port assigned, then we also need to talk about where is a good place to display that to the user. 

Thoughts?

**Comment by maths22** [comment]
That pseudocode seems reasonable (other than the recursive try/catch).  IMO 8080 is a good second try, and after that, just increment by 1.  That region is pretty sparse in terms of standard applications using those ports, and at least I tend to run things on 8081, 8082, etc if I already have something on 8080.  I'm thinking you could display the URL at the top of the page, so it is nice and visible for scorekeepers/for one referee to show their neighbor/etc.

![image](https://user-images.githubusercontent.com/3067361/46764223-82240600-cca1-11e8-83ef-428b62969472.png)

**Comment by cmacfarl** [comment]
What Jacob said sounds good.

The URL display however should show the ipaddress of the server instead of localhost.  That's precisely however where I was thinking of putting it.

**Comment by ftctechnh** [comment]
In the interim, the user documentation now includes instructions on how to launch the software using an alternate port for situations where the default port is unavailable or the user's account (on a Mac) does not, for example, have administrative privileges.

**Comment by adwiii** [comment]
The server now checks progressive ports until it finds one. My intention was that the Mac would still ask for root permissions, and if that check failed then it would move to a different port. However, it appears that for some reason when the permissions check fails the process stops. I will continue investigating this.
