### ISSUE TITLE
Silk browser support

### ISSUE THREAD

**Issue by tweirtx** [FIRST-Tech-Challenge/scorekeeper#589]
** Requested Change **
The Silk browser included with Fire tablets should not be called out as "unsupported" due to the fact it really is just re-skinned Chromium.
![image](https://user-images.githubusercontent.com/17951807/200981145-0031a97b-ed4d-4d7d-b524-60e6b3c42ded.png)
![image](https://user-images.githubusercontent.com/17951807/200981227-794f817a-8327-4537-bb02-31c839f1d70a.png)

** Relevant existing documentation **
[Page 14 of the Scorekeeper Guide](https://firstinspiresst01.blob.core.windows.net/first-energize-ftc/scorekeeper-guide.pdf)

**Comment by jvens** [comment]
Technically this argument applies to any browser built on Chrome/Chromium (e.g. Edge, Opera, Brave, etc.).  It is important to remember that just because a browser is built on Chromium, each implementation can add or change aspects of it which may break compatibility (rare, but possible).

As far as Silk and Fire Tablets go, I have noticed issues getting them to scan the QR codes for field inspections, but I haven't dug into if that is an issue with the browser, the tablet hardware, or tablet software settings yet.

All that said, given how many regions use fire tablets, and how well they seem to work with the system (QR code scanning excepted) I second making silk an officially supported browser and adding it to whatever list of devices you run regression testing on for releases.

**Comment by tweirtx** [comment]
Anecdotally, my Samsung tablet running Chrome has not been able to process inspection QR codes either. I'm not sure it's fair to blame that on Silk.

**Comment by pmichaud** [comment]
> https://www.amirror.com/apk/google-inc/chrome/ 

FWIW, that link gives me a 404 Not Found error.

Pm

**Comment by mcchesneyc** [comment]
apkmirror.com/apk/google-inc/chrome/
Try cutting and pasting this link without the "https://www."  Or - search for apkmirror chrome on Google

**Comment by pmichaud** [comment]
> It's easy enough to sideload the current version of Google Chrome onto any Fire Tablet using APKMirror. 

More generally, "easy enough" depends on a person's skill at Android device management.  I'm quite an experienced computer person but I haven't been able to find any clear, easy to follow instructions on how to do this.  Once someone gets to APKMirror, they have to figure which one of the hundreds of files available they need to download for the Kindle Fire.  Then you have to get the .apk onto the tablet of course.  From there it's generally easy, yes -- allow apps from unknown sources and then you're good to go.

But rather than make every FTA/scorekeeper in FTC have to learn another procedure, keep updated based on changes to the Kindle and Android ecosystems, and repeat that procedure on dozens of devices (we have almost 50 in North Texas alone)... why not just test/support chromium-based Silk at the source since the devices are so popular?

Pm

**Comment by KevinEmery** [comment]
This is the guide I followed to install Chrome on my new tablets earlier this week: https://www.howtogeek.com/232726/how-to-install-the-google-play-store-on-your-amazon-fire-tablet/ 

Anecdotally as a software engineer I didn't find it easy, but it was doable. Those instructions show how to install the Play Store (through four separate APKs in order to get Google Services installed) and then from there it's like any Android tablet. And I'll also add another note to the "used Silk for years" pile with no real issues to my knowledge.
