### ISSUE TITLE
Meet (Event) Rankings

### ISSUE THREAD

**Issue by vchposton** [FIRST-Tech-Challenge/scorekeeper#599]
**Is your feature request related to a problem? Please describe.**
The "Event Rank" under Event Info > "(League) Rankings" is misleading.  I think "Event Rank" should reflect team rankings at that event only.  What "Event Rank" means on that page is still the _overall_ "League Rank", but omitting teams that were not at that meet.  Not very useful, and if a true Event Rank can't be calculated, then that column should just be dropped.

The same issue exists on the Match Results page displayed to the audience.  In the below screen, 15903 is shown as 4th in Event Rank, but they have a 1-4 meet record for a 0.2 RP.  21632 is 5th, but their meet record is 3-2, for a 0.6 meet RP.  The audience expects that 15903 has done better that 21632 in the meet but they haven't.

![Capture](https://user-images.githubusercontent.com/7231244/206636864-5280263e-e3eb-4953-858e-7b7ec7bb209e.PNG)

**Describe the solution you'd like**
"Event Rank" should show the rank of teams _at that event (meet)_. 
Ideally, I'd like to see an Event Results page that has RP/TB1/TB2/High score _at that event (meet)_.  League Rankings would show the overall League Rankings.
I'd like to see Event Rank on the audience display to show rank for that event only.

**Describe alternatives you've considered**
I hand calculate meet rank for recaps, but can't do anything about audience display.

**Additional context**

**Comment by vchposton** [comment]
I hope that my explanation makes sense, but I'm going to try an analogy.

Consider the Bizarro World Series, where during each game, you don't see the runs scored in that game, but just the average runs scored in the series.  Who won that individual game?

That's kind of what we're getting with the current Event Rank.

**Comment by jvens** [comment]
The event rank shows the current rank in the league of all the teams in the event.  This is so if you have a lot of teams missing (common in some states with very large league sizes and the expectation not all teams play every meet) you don't have to wait for it to scroll through all the teams not there to find your teams rank.  However, the only ranking that makes sense in the league system is the rank in the league.  Ranking for a given meet doesn't actually matter for anything and showing the ranking only for a meet would not be useful to the teams.  Teams like to see where they rank overall in the league because when it come to the league tournament that sets their starting rank going into the event, and eventually their final rank going into alliance selection.

Your World Series analogy is not a good fit for the FTC League system.  Think of league meets as one big event spread across multiple days.  So it would be like if in the world series they played the first 3 innings on the first week, the second 3 innings the second week, and the final 3 innings the third week.  During week three it doesn't really matter how the team does in those 3 innings, it only matters how they have done in the combination of all 9 innings for determining the winner.

**Comment by maths22** [comment]
Also, if you don't find the event rankings to be valuable for your leagues, you can hide them by unchecking this checkbox on the settings tab on the match control page (it should say "event rankings" not "meet rankings"; we'll correct the label in a future release):
<img width="482" alt="image" src="https://user-images.githubusercontent.com/3067361/206638616-8ed5dfff-9b70-47a7-a67d-cdc57294c6fb.png">

**Comment by vchposton** [comment]
> Also, if you don't find the event rankings to be valuable for your leagues, you can hide them by unchecking this checkbox on the settings tab on the match control page 

Thanks.
