### ISSUE TITLE
Make it easier to edit team information

### ISSUE THREAD

**Issue by jvens** [FIRST-Tech-Challenge/scorekeeper#65]
It is not possible to edit team information in the `Manage League` section which seems like something that should be possible.  Also, it is not intuitive that to edit information about a team you have to go to `Add/Edit Teams` and then click `Add Individually`.  Just add another tab for `Edit Teams`.  Also, when you click the `edit` button on the `Add Individually` tab and make changes it is not obvious that you have to click the very small `save` button for those changes to be saved.  I recommend when you click the `edit` button that a modal dialog box pops up that you can edit the team info in and then click a `save` or `cancel` button.

**Comment by adwiii** [comment]
The issue on editing within the league flow is how team edits are stored. Team name edits are stored on the event level instead of the league level, which means that when the league data is sent to the next league event, it does not contain edited team names. This is to remove an extra level of complication if the names were to have been entered differently at different league events.


I will look into improving the UI flow for editing.

**Comment by maths22** [comment]
Barring exceptional circumstances, team data should no longer be edited through the local scoring system, and leagues can no longer be managed in this way.
