### ISSUE TITLE
Awards Manager error - "e is undefined"

### ISSUE THREAD

**Issue by nickdrones** [FIRST-Tech-Challenge/scorekeeper#667]
Awards Manager throwing error when team is selected, no error when only the award is selected

1. Set up match and enter team numbers into Awards Manager
2. Click on "Present Awards"
3. Click the Award name, it will display with no error
4. Click the team number under the award name, the error will occur

I don't know what the screen is supposed to look like so I'm not sure what the anticipated behavior would be, I assume it would just add the team number to the lower third

![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/16674954/986055df-ac3a-49d7-ac24-7f522244cd2b)

 - OS: Windows 10 and 11
 - Browser: Chrome and Firefox
 - Version: 5.1.2

**Comment by adwiii** [comment]
While the display still should not throw an error in this case, the root of this issue comes from trying to show an award for a team that has no team name. This will be fixed in the next release, but this is unlikely to affect events given the criteria to hit the error. In the interim, if you must show a team without a team name, you can enter ` ` (a space) for the team name.
