### ISSUE TITLE
Create off-season Event in the offical scroing system

### ISSUE THREAD

**Issue by MElkmeshi** [FIRST-Tech-Challenge/scorekeeper#731]
**Describe the bug**
There's a off-season event type in the offical system and I didn't knew there's another scoring system 
![image](https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/95718825/ed930d3e-6598-43f9-a27f-23fd83373f0c)

**Comment by timtim17** [comment]
Not sure what the bug is here. Anyone can create an offline event locally using FTC Live, and can configure it accurately as an "off-season."

If you wish to list it on the online system/FTC Events, you will need to apply for support from *FIRST* HQ or be supported by your PDP. https://www.firstinspires.org/sites/default/files/uploads/resource_library/ftc/off-season-events.pdf

**Comment by maths22** [comment]
Offseason events can be run in the regular in-season scoring system.  We do have a specific offseason release of the scoring system that *only* allows running offseason events because it relaxes some of the constraints of the regular scoring system (more or fewer matches per team than normal, importing custom schedules, team numbers 99900-99999 for unregistered teams), but if you are not trying to take advantage of any of those features the regular release of the scoring system will work fine and is supported for such events.
