### ISSUE TITLE
location of saved league files

### ISSUE THREAD

**Issue by rgutentag** [FIRST-Tech-Challenge/scorekeeper#74]
When a league file is saved it is put in the download directory.  Could we have an setting option to specify what directory we would like the file saved in.

**Comment by adwiii** [comment]
Closing as league management is deprecated in FTCLive. All league data is handled through the [online scoring system](https://ftc-scoring.firstinspires.org) and automatically imported when the event is imported into FTCLive. Because of this, all league events ***must*** upload results to the online scoring system.
