### ISSUE TITLE
Is there a limit on the file path name length of where the software installed

### ISSUE THREAD

**Issue by ftctechnh** [FIRST-Tech-Challenge/scorekeeper#86]
User has windows laptop with hierarchy of folders.  He had the score software installed in a sub folder, but it wouldn't run until he moved it to deskop.

**Comment by cmacfarl** [comment]
Could be a problem with spaces in directory names.  Spaces in filesystems are evil.

**Comment by adwiii** [comment]
Windows has a built in limit of 260 characters. It was my understanding that Windows would warn you when unzipping that you were creating a file that was too large and it would not allow that file to be created - there would be no middle ground of "the unzip was successful, but the file did not run". As shipped right now, I believe the longest path in the software is 227 characters long, which leaves only 30ish characters left for the user to specify parent directories.

I will do some additional digging and figure out what file is so long and if there are steps we can take to reorganize and reduce its path length.

**Comment by adwiii** [comment]
Ah, this appears to be related to #72. I am working to remove un-needed files for that issue, and after that improvement, the longest path name will be ~158 characters, which will allow over 100 characters of the user's subfolder structure.

**Comment by ftctechnh** [comment]
2 users encountered this problem when testing this past week.

**Comment by adwiii** [comment]
Hm. I seem to be wrong - I just forced this problem to occur and it did happen that unzip went smoothly but it could not run. I will see if there is a way that we could detect this issue and give a more helpful error message to the user.

**Comment by deliana-d** [comment]
This is because the batch script is hitting the Windows command line string length limit. See https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation for more details.

Line 72 of FIRST-Tech-Challenge-Live.bat which is setting the Java CLASSPATH is hitting this limitation if the expanded %APP_HOME% variable is too long.

Quick workaround for users would be to unzip to a folder on their Desktop instead of a nested file structure.

Two fix options I could see for the code:
1. In line 14 of FIRST-Tech-Challenge-Live.bat, use the relative path instead. That is, change the line from "set APP_HOME=%DIRNAME%.." to "set APP_HOME=.."
2. Require Java 6 and use wilcards in CLASSPATH, as per https://docs.oracle.com/javase/6/docs/technotes/tools/windows/classpath.html. That is, add code to check minimum Java version and change the current line 72 to "set CLASSPATH=%APP_HOME%\lib\;%APP_HOME%\lib\*;%APP_HOME%\lib\resources;%APP_HOME%\lib\MatchMaker;"
3. Check what the length of the %APP_HOME% variable is set to, do some math to see what that would set the CLASSPATH variable to (currently, I believe it is "length of %APP_PATH%"x55+1666) and echo a more detailed error message (i.e. suggesting that the user unzip to a folder on the Desktop instead) and quit gracefully

**Comment by adwiii** [comment]
I will take a look at that, thanks! We currently require Java 8 anyway for other requirements, so that should not be a problem.

**Comment by maths22** [comment]
We now use wildcards in our classpath.
