### ISSUE TITLE
League Meets and Abort Match

### ISSUE THREAD

**Issue by bbugert** [FIRST-Tech-Challenge/scorekeeper#89]
Two issues found.
1. After entering a league I can't figure out how to add each meet and the dates.

2. During a test of the software. I tried aborting the match at different points (Autonomous or Teleop) and the "Abort" button would not respond and sometime jammed the page then had to refresh the page.

Attached is a zipped copy of the db
[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/2494501/db.zip)

Release: FIRST-Tech-Challenge-Live-0.4.1
on a HP laptop with Windows 10 in IE browser
.

**Comment by adwiii** [comment]
Can you try the abort operation again in Chrome? This may be a compatibility issue.

**Comment by bbugert** [comment]
Thank you, yes Chrome did solve the issue of "Abort".

How about the League Meets under "League Management", I can't figure out how to enter the meets and there corresponding dates.

**Comment by adwiii** [comment]
Are you trying to import league data from a previous meet into another meet?

**Comment by adwiii** [comment]
From this page:
![image](https://user-images.githubusercontent.com/9453262/47221626-e8381980-d382-11e8-9fe4-0c0f84758cd7.png)
you can select a file to upload. First, select the "Choose File" button and then use the file dialog to choose a `.db` archive file from a previous league meet. Then, select "Import League Data". This will import all leagues and all meet data that the previous event knew about, including the previous event itself. Before completing the import, the page will tell you what data will be imported, as shown below:
![image](https://user-images.githubusercontent.com/9453262/47221926-90e67900-d383-11e8-928f-f52d3a5c61b9.png)
You then have the option to continue with the import or cancel. 

One point here - you don't need to add *individual* meets. Say you have league meet 1, league meet 2, and league meet 3 in your region, and the same group of teams plays all three of those leagues. At league meet 1 you don't need to import any previous data. Then at league meet 2 you need to import the archive file from league meet 1. Then, at league meet 3, you only need to import the archive for league meet 2 because the archive for league meet 2 includes the relevant data from league meet 1 already.

**Comment by bbugert** [comment]
Thank you, I understand now how to do the league.
